### ISSUE TITLE
Azure provider: Unexpected audience causes invalid bearer token

### ISSUE THREAD

**Issue by betabandido** [pusher/oauth2_proxy#105]
I am using oauth2_proxy behind Kubernetes ingress nginx to allow users of the cluster to access its dashboard.

Pretty much everything seems to work well (e.g., the authentication bearer token is correctly forwarded to the dashboard from nginx). But the token obtained from Azure contains the wrong audience (at least from the point of view of what Kubernetes expect). I can see the following error message in the cluster master node:

```
E0317 17:13:21.837365       
1 authentication.go:62] Unable to authenticate the request due to an error: 
[invalid bearer token, 
[invalid bearer token, oidc: verify token: 
oidc: expected audience "spn:{redacted client ID}" got ["https://graph.windows.net"]]]
```

As the message says, the token returned by oauth2_proxy does not have the client ID in the audience field. Instead, it has the audience set as `"aud": "https://graph.windows.net"`.

Following https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-openid-connect-code I have created a small program that queries Azure to obtain the ID token. Instead of setting the `response_type` to `code` (as oauth2_proxy does) I used `id_token` and the ID token that I got back had the correct audience set (`"aud": "{redacted client ID}"`). The response misses the `spn:` prefix, but that is a known issue tracked at https://github.com/kubernetes/client-go/issues/566 (it seems that missing the prefix is actually correct, and Kubernetes is expecting the old audience format).

## Expected Behavior

The obtained ID token has its audience set to the client ID.

## Current Behavior

The obtained ID token has its audience set to `https://graph.windows.net`.

## Possible Solution

Perhaps allowing a flow that simply fetches the ID token (setting `response_type` to `id_token`) could solve this issue.

## Context

For completeness, I had a look at how Kubernetes verifies the tokens, and this is what I found:

OIDC token verification in Kubernetes is done here:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go#L559

The verifier uses `coreos/go-oidc`, and the verification itself expects the client ID to be part of the audience. See:
https://github.com/coreos/go-oidc/blob/master/verify.go#L164

## Your Environment

- Version used: latest

**Comment by JoelSpeed** [comment]
I'm wondering if you could attempt to set up the OIDC provider to point to azure? You could try the OIDC issuer as `https://login.microsoftonline.com/<tennant>` and see what happens?

**Comment by maxh8086** [comment]
Pointing to Similar resolution of ADFS : 

https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code

**Comment by betabandido** [comment]
@JoelSpeed I have tried using the OIDC provider, but I have run into a few issues.

First, the issuer returned by Azure is not the same as the one sent. So, I get the following error from https://github.com/coreos/go-oidc/blob/v2/oidc.go#L123

```
oidc: issuer did not match the issuer returned by provider,
expected "https://login.microsoftonline.com/<tennant-id>
got "https://sts.windows.net/<tennant-id>/"
```

I manually disabled the check in the `go-oidc` library and the different provider parameters (authURL, tokenURL, etc.) seem to be actually obtained successfully.

The second problem occurs at https://github.com/pusher/oauth2_proxy/blob/master/providers/oidc.go#L119

The token returned by Azure does not contain the email in the `sub` field (it is instead in the `upn` field). That means I cannot specify email addresses with `-email-domain=<some domain>`.

I hardcoded the email, compiled again and after running the proxy again, the authentication was completed successful.

Given that fixing one of the issues involves changing the `go-oidc` library, it is not clear to me whether there is an easy fix for this issue. What do you think?

**Comment by ploxiln** [comment]
It seems like OpenID-Connect is just as inconsistently implemented as Oauth2, and separate "provider" code tends to be needed for each ... it's just especially unfortunate that there seems to be 2 or 3 different Microsoft products with "Azure" in the name that all need different "provider" code to handle their quirks.

**Comment by maxh8086** [comment]
Microsoft expect resource (Actual consumer of Token ) to be included in every request sent by oauth2 proxy to respond right audience.. same happens in ADFS.. sample output has been shared for adfs request.

**Comment by betabandido** [comment]
@maxh8086 I suppose that is only the case for the oauth2 code grant, but not for the openid protocol (documentation does not list any `resource` field in the request for the latter).

I can confirm that using the oauth2 code grant (where an extra request is needed to get the token) returns a token with the audience containing the `spn:` prefix. For this to work I believe it is needed to specify `spn:your client id` as the resource field in the first request, and then use `api-version: 1.0` in the second request (to exchange the obtained code for the token).

**Comment by maxh8086** [comment]
For Microsoft resource is web api who is intent to consume the token. Yes you are true openid do not have it documented in a way that tells resource in grant type code / authorization code.. but this is how Microsoft has implemented its ADFS / Azure AD.. although i believe it clears the intention of token requesting application that code will be consumed by third party (kubernetes API) not by requestor (proxy). This has been tested with other app with to the help of application owner.. and able to get all custom grant using method stated by Microsoft article.

**Comment by Fez29** [comment]
@JoelSpeed @ploxiln I suspect the issues I am having with Azure AD are related to the issues mentioned in this post.  #502 I am seeing very similar behavior with issues with the issuer, audience etc.

**Comment by AMoghrabi** [comment]
Hi @betabandido. Did you end up solving this problem? I get the same error as you:

```
Unable to authenticate the request due to an error: [invalid bearer token, oidc: verify token: oidc: expected audience "spn:{client_id}" got ["{client_id}"]]
```

**Comment by betabandido** [comment]
@AMoghrabi No, I didn't. A little after reporting this I stopped using Azure to authenticate, so I didn't continue looking for a solution.
