### ISSUE TITLE
Basic auth not working on v3.1.0

### ISSUE THREAD

**Issue by egezonberisha** [pusher/oauth2_proxy#118]
## Current Behavior

When using the basic auth does not move passed the login page, even though it does authenticate (see log below)
log file:
```
oauth2_proxy[22171]: 2019/04/02 14:33:12 main.go:125: using htpasswd file /etc/oauth2_proxy/htpasswd
oauth2_proxy[22171]: 2019/04/02 14:33:12 http.go:52: HTTP: listening on 127.0.0.1:4180
.
.
.
oauth2_proxy[22171]: 2019/04/02 14:33:25 oauthproxy.go:557: authenticated "testuser" via HtpasswdFile
2019/04/02 14:33:25 oauthproxy.go:796: 127.0.0.1:54202 ("11.32.107.32") invalid number of fields (got 1 expected 5)
```
## Steps to Reproduce (for bugs)

Using a config file 
```
htpasswd_file = "/etc/oauth2_proxy/htpasswd"
```
Note that it successfully authenticates, but doesn't advance passed the login page. 

Everything was working on version v2.0.0 and the only thing that changed was the upgrade to v3.1.0

- Version used:
oauth2_proxy --version
oauth2_proxy v3.1.0 (built with go1.11)

**Comment by ploxiln** [comment]
session state format has changed in this fork ... but for some explanation of the problem and type of fix see https://github.com/ploxiln/oauth2_proxy/pull/1
