### ISSUE TITLE
Issue with cookie_secret when upgrading from v3.1.0 to v3.2.0

### ISSUE THREAD

**Issue by Ghazgkull** [pusher/oauth2_proxy#126]
I just tried upgrading an existing oauth2_proxy deployment from version v3.1.0 to v3.2.0 and the application now fails to start with the following log output:

2019/04/12 23:08:12 main.go:120: Invalid configuration:
  cookie_secret must be 16, 24, or 32 bytes to create an AES cipher when pass_access_token == true or cookie_refresh != 0, but is 236 bytes.

## Expected Behavior

A minor version increase should contain only non-breaking changes.

## Steps to Reproduce (for bugs)

1.  Generate a cookie secret using the recommended: `python -c 'import os,base64; print base64.urlsafe_b64encode(os.urandom(16))'`
2.  Upgrade from v3.1.0 to v3.2.0

## Your Environment

Running oauth2_proxy in a kubernetes pod via the Helm chart, but specifying v3.2.0 for the image tag.

**Comment by JoelSpeed** [comment]
Hey @Ghazgkull, I've had a look at this issue this morning and have been unable to reproduce your error.

As far as I'm aware there should not have been any changes to the code that handles parsing in the secrets in this way. The code that processes it is: https://github.com/pusher/oauth2_proxy/blob/ee4ebe53bf1234265b838076760dc72b5d92d32e/options.go#L239-L262 

What has changed to do with options in this release is the fact that every option now has an environment variable, though the `cookie_secret` had one already so I can't see why that would have changed. How are you loading your cookie secret into the application? Via environment, flag or config file?

**Comment by JoelSpeed** [comment]
@Ghazgkull Did you manage to solve your issue?

**Comment by Ghazgkull** [comment]
Hi, @JoelSpeed. My apologies for the delayed response. It took a while for this issue to get resolved and it turned out to completely be a configuration issue on our end, where our Kubernetes secret started being deployed incorrectly such that the secret value was stored as "null".

It was not a problem with oauth2_proxy.
