### ISSUE TITLE
ErrorPage 403 Permission Denied http: named cookie not present

### ISSUE THREAD

**Issue by mikeeh24** [pusher/oauth2_proxy#132]
This is likely more of a usage question but I've scoured the internet around this issue and tried everything I can think of to no avail.  

After successfully authenticating with Azure AD oauth2 I get:

`2019/04/16 14:39:48 oauthproxy.go:532: ErrorPage 403 Permission Denied http: named cookie not present`

I'm running my main application, oauth2_proxy, and nginx all on the same server.  

**My main application is a Go app running at "0.0.0.0:4000"**  

**My oauth2_proxy config is:**
```shell
    http_address = "0.0.0.0:4180"
    redirect_url = "https://dashboard.mycompany.com/oauth2/callback"
    upstreams = [
        "http://0.0.0.0:4000/"
    ]
    email_domains = [
         "*"
     ]
    client_id = "[hidden]"
    client_secret = "[hidden]"
    provider = "azure"
    azure_tenant = "[hidden]"
    ssl_insecure_skip_verify = true
    cookie_secret = "[hidden]"
    cookie_domain = ".mycompany.com"
    cookie_expire = "24h"
    skip_provider_button = true
```

**My nginx.conf looks like:**
```shell
    http {
      server {
        listen 443 ssl;
        server_name dashboard.mycompany.com
        ssl_verify_client off;
        ssl_certificate      /[hidden]/[hidden].crt;
        ssl_certificate_key  /[hidden]/[hidden].key;
        add_header Strict-Transport-Security "max-age=31536000" always;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_session_cache   shared:SSL:40m;
        ssl_session_timeout 24h;
        ssl_session_tickets on;
        location / {
            proxy_pass http://0.0.0.0:4180;
            proxy_set_header Host dashboard.mycompany.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
            proxy_connect_timeout 1;
            proxy_send_timeout 30;
            proxy_read_timeout 30;
        }
      }
    }
```

I'm using the latest version of oauth2_proxy.  I'm testing in a Chrome private session.  Thank you for any help.

**Comment by timothy-spencer** [comment]
I notice that you have one instance of "dasboard.mycompany.com" up there, but I suspect that's a typo.  What I bet is happening is that your cookie_domain needs to be set to "dashboard.mycompany.com" instead of ".domain.com".

**Comment by mikeeh24** [comment]
Yes, sorry, in my attempt to hide some of the exact values I'm using I typoed that.  My cookie_domain value should show as ".mycompany.com" but I also tried "dashboard.mycompany.com".  Same error either way.

**Comment by ploxiln** [comment]
another typo which is possibly just in your example and not in your actual config:

```
redirect_url = "https://dasboard.mycompany.com/oauth2/callback"
```

After successful auth on the provider's page, you're supposed to be redirected back to this redirect url, with a url param "code=..." and your browser should also have a CSRF cookie (default "_oauth2_proxy_csrf"). If you hit that redirect url with those two elements, it should finally give you a "_oauth2_proxy" cookie and redirect you to the original destination (or else "/"). If in the request after this callback, whether it is successful or fails, you don't seem to have the "_oauth2_proxy" cookie, you get that error message you originally posted.

I suggest posting more of the surrounding logs, they may have the cause. You can also use the browser debugging tools to look at the series of requests your browser makes, and what cookies they include.

**Comment by mikeeh24** [comment]
Thanks ploxiln, yes, that was a typo (fixed now).  Pouring over this a little more the app is successfully calling `https://login.microsoftonline.com/{tenant}/oauth2/authorize?` and is getting back a `code`.  What I'm not seeing is a clear call to `https://login.microsoftonline.com/{tenant}/oauth2/token`.  It seems it is failing before making the call to `/oauth/token`.  It's unclear to me as to why.  

**oauth2_proxy log**
```shell
# ./oauth2_proxy -config=/etc/oauth2_proxy.cfg
2019/04/17 10:19:20 oauthproxy.go:188: mapping path "/" => upstream "http://0.0.0.0:4000/"
2019/04/17 10:19:20 oauthproxy.go:212: OAuthProxy configured for Azure Client ID: [hidden]
2019/04/17 10:19:20 oauthproxy.go:218: Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domain:.mycompany.com path:/ refresh:disabled
2019/04/17 10:19:20 http.go:91: HTTP: listening on 0.0.0.0:4180
2019/04/17 10:19:34 oauthproxy.go:830: 127.0.0.1:41490 ("10.0.12.18") Cookie "_oauth2_proxy" not present
10.0.12.18 - - [17/Apr/2019:10:19:34 -0500] dashboard.mycompany.com GET - "/" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" 302 364 0.000
2019/04/17 10:19:51 api.go:22: 200 GET https://graph.windows.net/me?api-version=1.6 {...[hidden, because it's huge, but returns an object with a bunch of details about my ID]...}
2019/04/17 10:19:51 oauthproxy.go:532: ErrorPage 403 Permission Denied http: named cookie not present
10.0.12.18 - - [17/Apr/2019:10:19:50 -0500] dashboard.mycompany.com GET - "/oauth2/callback?code=[hidden]&state=653924248883c8c189038d2248662557%3a%2f&session_state=de4d83fa-cb14-49cb-9c8a-2ec660d81042" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" 403 353 0.800
```

There are no errors in the /var/log/nginx/error.log file. Let me know what else you might want to see.  Again, I appreciate the help.

**Comment by ploxiln** [comment]
I think you may be hitting this case:

```go
	c, err := req.Cookie(p.CSRFCookieName)
	if err != nil {
		p.ErrorPage(rw, 403, "Permission Denied", err.Error())
		return
}
```

**Comment by mikeeh24** [comment]
Thanks ploxiln, that got me going in the write direction.  I was able to figure out the issue.  Turns out my redirect URL was the FQDN of the host but when I was testing this in the browser I was simply using the shortname.  Once I tried the FQDN in the URL it worked.  So I added the following in my nginx.conf server block:

```shell
    if ($host != $server_name) {
      rewrite ^/(.*) https://$server_name/$1 permanent;
    }
```
Thank you!

**Comment by dmahisingh** [comment]
Hello, I am also facing this issue - I saw your comments, you said it got fixed by writing above one in nginx.conf. 
Which nginx.conf you are referring here? I just created pod, service and ingress for oauth2 proxy, so not sure which nginx you are referring to.
Can you please guide me on the same?
