### ISSUE TITLE
Question: Is it possible to put GitLab behind oauth2-proxy?

### ISSUE THREAD

**Issue by jeremych1000** [pusher/oauth2_proxy#134]
Quick question - what kind of applications do not work behind oauth2-proxy? 

I'm looking to deploy GitLab (open source version) behind oauth2-proxy, but oauth2-proxy would break HTTPS git clone/pushes - it tries to redirect to the oauth2 endpoint, as my terminal is not authenticated (is that correct?)?

I'm aware that GitLab supports direct oauth2 authentication, but a client requirement is all apps behind oauth2-proxy.

Has anyone had any experience doing this?

**Comment by brianv0** [comment]
No experience but if you use an OpenID Connect provider you can probably use the JWT OmniAuth provider.
