### ISSUE TITLE
Migrate CI to Prow from Travis

### ISSUE THREAD

**Issue by JoelSpeed** [pusher/oauth2_proxy#139]
## Expected Behavior

CI should help us to triage, test and release the project. 

## Current Behavior

We are currently making little use of Travis and it also has some problems (eg users can't rerun tests)

## Possible Solution

Pusher now have an instance of [Prow](https://prow.pusher.com) which is used for our Open Source projects. We could make use of this Prow instance to run builds and tests and automate image pushing and building of release artifacts to make releasing easier.

Along with this, Prow will help to keep issues from going stale, allow users to interact with the bot to ask for tests to be run again etc

Any thoughts on this @syscll @gargath?

**Comment by syscll** [comment]
Sounds like a good idea! Would be interested to learn a little more about Prow first, though. Fancy giving a demo some time? :upside_down_face:

**Comment by JoelSpeed** [comment]
> Fancy giving a demo some time? 🙃

Want to come over to the Pusher office some time next week? Happy to demo what we have already set up

**Comment by JoelSpeed** [comment]
If anyone is familiar with Prow's configuration syntax (or wants to learn it) then we have our Prow config at https://github.com/pusher/testing and a PR to that could add OAuth2 Proxy to our Prow instance

**Comment by JoelSpeed** [comment]
We decided against this
