### ISSUE TITLE
Prebuilt binary tarball format has changed from bitly

### ISSUE THREAD

**Issue by zeha** [pusher/oauth2_proxy#162]
The tarballs used to have this format:

`./<tarball-base-name>/oauth2_proxy`

Now they contain:

`./release/oauth2_proxy-<platform>`

## Expected Behavior

A tarball named `oauth2_proxy-v3.2.0.linux-amd64.go1.11.tar.gz` should have a single file named `oauth2_proxy-v3.2.0.linux-amd64.go1.11/oauth2_proxy`.

## Current Behavior

The tarball has `release/oauth2_proxy-linux-amd64`

## Steps to Reproduce (for bugs)

Download the tarball from https://github.com/pusher/oauth2_proxy/releases/download/v3.2.0/oauth2_proxy-v3.2.0.linux-amd64.go1.11.tar.gz and compare with https://github.com/bitly/oauth2_proxy/releases/download/v2.2/oauth2_proxy-2.2.0.linux-amd64.go1.8.1.tar.gz

## Context

We're using this puppet module to deploy oauth2_proxy, and it expects the old format:
https://github.com/jhoblitt/puppet-oauth2_proxy

Would be great to not have to modify the module in a backwards-incompatible way.

## Your Environment

- Version used: 3.2.0

Thank you for maintaining oauth2_proxy!

**Comment by JoelSpeed** [comment]
This is a very good point, thanks for raising the issue! I'll see if anyone at @pusher has any time to sort this, unless anyone else has a spare half hour to fix the `make release` target that builds these tarballs?

**Comment by zeha** [comment]
I've typed in the `Makefile` changes :)
