### ISSUE TITLE
Docs wording

### ISSUE THREAD

**Issue by pablopla** [pusher/oauth2_proxy#164]
This sentence in the [configuration docs](https://pusher.github.io/oauth2_proxy/docs/configuration) need to be rephrased:
```
that will **forward** all authenticated requests to be **forwarded** to the upstream server
```

**Comment by JoelSpeed** [comment]
Yeah that makes no sense! In fact, I'm not sure what the whole paragraph is trying to get across 🤔 

Perhaps it should just be:
```
HTTP and HTTPS upstreams are configured by providing a URL such as http://127.0.0.1:8080/ for the upstream parameter, this will forward all authenticated requests to the upstream server.
```

**Comment by pablopla** [comment]
When using <code>http://127.0.0.1:8080/some/path/</code> will the path be stripped when forwarded to the upstream?
Do we need a trailing / for a single upstream? <code>http://127.0.0.1:8080/</code>
