### ISSUE TITLE
TLS Configuration docs

### ISSUE THREAD

**Issue by pablopla** [pusher/oauth2_proxy#165]
The two configurations in the [TLS Configuration](https://pusher.github.io/oauth2_proxy/tls-configuration) docs are both numbered 1:
```
1. Configure SSL Termination with OAuth2 Proxy...
1. Configure SSL Termination with Nginx...
```

This paragraph is related to the first configuration but appears in the nginx configuration:

> Because oauth2_proxy listens on 127.0.0.1:4180 by default, to listen on all interfaces (needed when using an external load balancer like Amazon ELB or Google Platform Load Balancing) use --http-address="0.0.0.0:4180" or --http-address="http://:4180".

**Comment by JoelSpeed** [comment]
You're correct, do you have time to send a PR to fix the ordering of the docs for this?

**Comment by cardoppler** [comment]
Bump
