### ISSUE TITLE
LinkedIn authentication is not working

### ISSUE THREAD

**Issue by asharabu** [pusher/oauth2_proxy#181]
Hi,
The LinkedIn authentication is not working and getting the below error. It was working earlier.

2019/06/07 12:58:06 api.go:22: 410 GET https://www.linkedin.com/v1/people/~/email-address?format=json {
  "errorCode": 0,
  "message": "This resource is no longer available under v1 APIs",
  "requestId": "JHCEXE8DN3",
  "status": 410,
  "timestamp": 1559912286270
}

**Comment by yrock** [comment]
I'm experiencing the same thing, with same error message. Using Oauth2_proxy 2.2.

**Comment by yrock** [comment]
Seems like LinkedIn terminated support for their v1 API:
https://engineering.linkedin.com/blog/2018/12/developer-program-updates 
Can anyone update Oauth2_proxy to use their v2 API? Greatly appreciated.
