### ISSUE TITLE
What's the recommend way for upstream systems to fetch the user identifier? 

### ISSUE THREAD

**Issue by yob** [pusher/oauth2_proxy#182]
We're experimenting with oauth2_proxy v3.2.0 in front of some ruby web applications to ensure all access is by authenticated users. We're using the OIDC provider, linked to auth0.

The proxy is started like this:

```
oauth2_proxy \
--provider=oidc \
--oidc-issuer-url=https://<subdomain>.auth0.com/ \
--upstream=http://localhost:5000 \
--http-address=0.0.0.0:4180 \
--cookie-secret=xxx \
--email-domain=* \
--skip-provider-button \
--pass-authorization-header
```

It works perfectly. Users loading the site over HTTP are redirected to auth0 to login, and then back to site where they gain access.

However, our ruby services are also interested in knowing who the user identified as. For that we need an email or other unique identifier. What's the recommended way to do so? We can see a few possibilities, but worry that if we guess we might get something that works but is insecure. 

1. Incoming requests have a `_oauth2_proxy` cookie set, which has some base64 JSON objects. The values of the JSON object appear to be encrypted though. Can we decrypt them somehow (maybe using the `--cookie-secret`)?

2. `--pass-authorization-header` means the incoming request has the IDToken embedded in the `Authorization` header. That IDToken is a JWT, which has the relevant details from auth0. Does oauth2-proxy automatically verify the signature of the IDToken (can we just decode the JWT and trust it)?

3. The incoming request has a `X-Forwarded-Email` header added to it. Can we just trust that value?

thanks!

**Comment by ploxiln** [comment]
Yes, you can use use and trust the `X-Forwarded-Email` (and `X-Forwarded-User`) headers.

**Comment by yob** [comment]
Thanks.

auth0 provide a [unique user identifier in the IDToken](https://auth0.com/docs/users/normalized/auth0/identify-users) that we might prefer to use over email address. Is Option (2) in my list safe as well, and do we need to validate the IDToken signature ourselves?

**Comment by starkers** [comment]
You may have a service that can provide (via a auth0 management API) additional features like password resets/bla bla.. for Auth0 for example the `user_id` is what u want (to start with) for sure.


I'm no expert but I think yes. Passing the JWT is quite a common.. its not uncommon to want that for several reasons..


- auth0 can have external connections (EG: azure AD).. you might want to embed meta-data about which groups the user is in (inside the JWT)
- at the application level itself (not just the transports... like nginx) its probably good security if u validate the JWT token.. (takes time to integrate/smooth over the first time)
- you may have a service in your application stack that do additional validations against the JWT

..eg.. unpack the JWT, look for "some" data and then check it with OPA to see what policies are applied.. (EG.. "what data can customer X see" etc)..  that'll give really fine grained powers to you.

(just stumbled over this issue as I was reading up on an auth0/oidc example... thanks for that, you saved me some time...)

**Comment by yob** [comment]
Thanks! I'll close this issue for now, I think we have enough context to continue integrating auth0 and oauth2 proxy
