### ISSUE TITLE
Getting encrypted access token from Azure AD

### ISSUE THREAD

**Issue by omeryesil** [pusher/oauth2_proxy#184]
First of all, I am sorry if this is a wrong place to post my issue..

I deployed oauth2_proxy on Kubernetes for our microservices. it uses Azure as provider. 

I am able to authenticate and get _oauth2_proxy cookie with token information, however, I see the access token and email values are encrypted, not sure if I am doing something wrong.   

## Expected Behavior
When I split oauth2_proxy cookie content with pipe delimiter ('|'), in the 0 index value I should see
`{
	"AccessToken": [JWT],
	"Email": [emailAddress]
	"CreatedAt": "2019-06-13T01:33:09.806116365Z"
}
`
## Current Behavior
I get the following content: 
```
{
	"AccessToken": [EncryptedJWT],
	"Email": [EncryptedEmail]
	"CreatedAt": "2019-06-13T01:33:09.806116365Z"
}
```
Both AccessToken and Email values come as encrypted, I am not able to base64 decode these values. 

## Context

My arguments are like these:

```
        - --provider=azure
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --azure-tenant=****
        - --client-id=****
        - --client-secret=****        
        - --cookie-secret=****
        - --pass-access-token=true 
```

##  Environment & Versions
Kubernetes 1.13.5, 
Azure Ad
quay.io/pusher/oauth2_proxy:latest

**Comment by omeryesil** [comment]
Ok, I changed the docker version from latest to v3.2.0, and I can get the token in the header (Access-Token) now.

**Comment by MedoDome** [comment]
Try to add "--set-xauthrequest"  

Pass Access Token wasn't populating X Auth Req Acess Token, I had to activate xauthreq

**Comment by omeryesil** [comment]
Yes, I tried "--set-xauthrequest" which returns the jwt in X-Auth-Request-Access-Token header, cookie's vlaue is encrypted. 

```
- --provider=azure
- --email-domain=*
- --upstream=file:///dev/null
- --http-address=0.0.0.0:4180

- --pass-access-token=true
- --set-xauthrequest=true 
```

I went through the code, having the cookie value opaque is more secure for SPAs.. However, in my case, I have both SPA and APIs , and I want to pass the token to the APIs for authorization while keeping the token encrypted in the browser.. Not sure how to do that (without using set-xauthrequest=true which makes the token readable in the browser)... 

May be I will implement decryption in my APIs, same as  https://github.com/pusher/oauth2_proxy/blob/master/cookie/cookies.go

**Comment by ploxiln** [comment]
There are options to pass the token upstream as well (assuming you use oauth2_proxy in proxy mode instead of in auth_request mode): `--pass-access-token` and `--pass-authorization-header`

**Comment by sneko** [comment]
Hi @ploxiln , I'm trying to set those values but I don't see any result. Could you please take a look at my case https://github.com/pusher/oauth2_proxy/issues/337#issuecomment-568146049 ? Thank you
