### ISSUE TITLE
unauthorized on kubernetes dashboard with google provider (invalid bearer token, Token has been invalidated)

### ISSUE THREAD

**Issue by lbvffvbl** [pusher/oauth2_proxy#19]
hi. we trying to use oauth2_proxy instead lua-resty-openidc (there are problem with refresh token)
kube-apiserver was configured with oidc 

>  - --oidc-client-id=XXX.apps.googleusercontent.com
    - --oidc-groups-claim=hd
    - --oidc-username-claim=email
    - --oidc-issuer-url=https://accounts.google.com

we build image from oidc branch as lbvffvbl/oauth2_proxy:v0.0.2 
(to Dockerfile was added 
RUN apt-get update
RUN apt-get install -y ca-certificates
)
but after configuration oauth2_proxy we see Unauthorized
in logs of kube-apiserver i see 

> Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Token has been invalidated]]

our deployment:

> apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dashboard-proxy
  name: dashboard-proxy
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dashboard-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dashboard-proxy
    spec:
      containers:
      - args:
        - --email-domain=domain.com
        - --upstream=http://kubernetes-dashboard.kube-system.svc.cluster.local
        - --http-address=0.0.0.0:8080
        - --provider=google
        - --redirect-url=https://HOST/oauth2/callback
        - --pass-authorization-header=true
        - --pass-basic-auth=false
        - --pass-access-token=false
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: OAUTH2_PROXY_CLIENT_ID
              name: oauth
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: OAUTH2_PROXY_CLIENT_SECRET
              name: oauth
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: OAUTH2_PROXY_COOKIE_SECRET
              name: oauth
        image: lbvffvbl/oauth2_proxy:v0.0.2
        imagePullPolicy: Always
        name: oauth-proxy
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /creds
          name: google-service-account
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

ingress:

> apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: kube-system
spec:
  rules:
    - host: HOST
      http:
        paths:
          - backend:
              serviceName: dashboard-proxy
              servicePort: 80
            path: /
  tls:
    - hosts:
        - HOST
      secretName: secret-tls

what we are doing wrong?

**Comment by JoelSpeed** [comment]
Could you add the `--set-authorization-header=true` flag to your deployment and then visit `https://$HOST/oauth2/auth` and read the `Authorization` header from the response? In the response should be the ID token that the OAuth2 Proxy is receiving from Google.

You can use jwt.io to decode this and take a look at the payload, double check your OIDC flags match the values in the payload.

**Comment by zmichael** [comment]
Looks like kube-apiserver can`t verify "web application" type token from Google, which is only can be used with oauth_proxy.
kubectl auth works fine with "Other" type, but with this type proxy can`t specify callback URL.

We will try your Dex branch as a Google IDP proxy.
