### ISSUE TITLE
Hide domains for google auth

### ISSUE THREAD

**Issue by steakunderscore** [pusher/oauth2_proxy#193]
## Expected Behaviour

When exposing oauth2_proxy to the internet we need to not list the domains that are valid to auth with. This is to stop leaking data about which external domains (customers) we are interacting with.

## Current Behaviour

Currently the following is printed, leaking details about which accounts are valid:

```
Authenticate using one of the following domains: @foo.com, @bar.com
```

## Possible Solution

I would propose we add a `-banner` flag (and associated `OAUTH2_PROXY_BANNER` env variable) which a custom banner could be set.

**Comment by JoelSpeed** [comment]
@steakunderscore Is this now ok to be closed?
