### ISSUE TITLE
Oauth2_proxy or Nginx-ingress something misconfigured

### ISSUE THREAD

**Issue by BondAnthony** [pusher/oauth2_proxy#197]
I'm using oauth2_proxy in Kubernetes to handle auth in front of Graylog. I'm using the Graylog SSO plugin that relies on trusted headers. I have oauth2_proxy configured to use OIDC and Auth0 as the provider. The connections between oauth2_proxy and Auth0 are working without any issues. The response sent back to Graylog from oauth2_proxy is working also and the required headers are being sent to the upstream Graylog service.

The issue: When using oauth2_proxy the requests to the upstream service are stalling out with TTFB timings in the minutes. Do I have something incorrectly configured that is driving this latency?

## Expected Behavior

When not using oauth2_proxy the graylog service loads without issues.

## Current Behavior

1 minute+ on mutilple requests to the graylog service when nginx-ingress is configured to use  oauth2_proxy for auth.

## Your Environment

Annotations enabled on my backend service.
```
    nginx.ingress.kubernetes.io/auth-response-headers: X-Forwarded-Email,X-Forwarded-User,X-Roles
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie_name_1;
      auth_request_set $user   $upstream_http_x_auth_request_email;
      auth_request_set $email  $upstream_http_x_auth_request_email;
      proxy_set_header X-Forwarded-User  $user;
      proxy_set_header X-Forwarded-Email $email;
      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "name_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
```

Oauth2_proxy configurations

```
        - --provider=oidc
        - --email-domain=mydomain.com
        - --oidc-issuer-url=https://mydomain.auth0.com/
        - --redirect-url=https://logs.mydomain.com/oauth2/callback
        - --upstream=https://logs.mydomain.com
        - --http-address=0.0.0.0:4180
        - --https-address=0.0.0.0:443
        - --pass-user-headers=true
        - --set-xauthrequest=true
        - --pass-authorization-header=true
        - --cookie-secure=true
        - --cookie-domain=logs.mydomain.com
        - --skip-provider-button
```

**Comment by ivelichkovich** [comment]
Use -set-xauthrequest

this will pass through
X-Auth-Request-Email
X-Auth-Request-User

had to dig through the code and do some tcpdumping to figure this out but hopefully it helps someone else

**Comment by hargut** [comment]
The key is, that as documented the `--pass-user-headers` flag only passes the information if it is already available in the auth request.
Whereby the `--set-xauthrequest` creates the header once the information is available.

The documentation is "clear" on that, but its really easy to oversee that detail. I was as well trying for some time until I found this issue...

**Comment by jkjha** [comment]
hey @ivelichkovich , not sure if you are still active here but many thanks to you. I was struggling from last 2 days to figure this out. You saved my day.
