### ISSUE TITLE
Feature request: Add support for starting a child process

### ISSUE THREAD

**Issue by jakajancar** [pusher/oauth2_proxy#200]
It would make things slightly simpler (e.g. in Heroku Procfile, Docker `CMD`, or just while developing) if oauth2_proxy could start a subprocess, similar to `sudo`, `authbind`, etc...

Bonus points if it sets `PORT` to a random port and automatically sets `--upstream` to `http://localhost:$PORT`.

Instead of:

```
#!/bin/bash

oauth2_proxy \
    --client-id ... \
    --client-secret ... \
    --cookie-secret ... \
    --email-domain foo.com \
    --upstream http://localhost:5000 &

PORT=5000 npm start &

wait -n
```

You could do:

```
exec oauth2_proxy \
    --client-id ... \
    --client-secret ... \
    --cookie-secret ... \
    --email-domain foo.com \
    npm start
```

eliminating an extra bash process on the way.

**Comment by steakunderscore** [comment]
Would it make more sense to solve this problem by running two different containers? Making use of something like [docker compose](https://docs.docker.com/compose/overview/) or two containers in a single pod in Kubernetes? To me having oauth2_proxy be able to fork processes seems a little dangerous, both stability and security wise.

**Comment by jakajancar** [comment]
Let's not assume that everyone is using containers or even k8s :) I also don't think you can do that on e.g. Heroku, and if you can, it's more expensive.

Don't understand where the danger comes from?

To me the biggest downside is feature creep (having to handle the signals for the child etc.)

**Comment by syscll** [comment]
While I understand why you might want this functionality, I feel like it is outside the scope of `oauth2_proxy` as it's more of an environment configuration problem.
