### ISSUE TITLE
ETA on cutting a New Release?

### ISSUE THREAD

**Issue by davidholsgrove** [pusher/oauth2_proxy#202]
Hi @joelspeed,

Do you happen to have an ETA on when a new tagged release might be expected?
Theres been some big changes since v3.7.0 in April, would be great to get a new cut :)

**Comment by JoelSpeed** [comment]
Hey @davidholsgrove, the next release is going to be a major one and as such, I've been trying to get all the breaking changes in aware of done and merged.

Unfortunately I've been quite busy on other urgent projects recently, but I should have some time next week to fix up #186, get that merged, and then cut a release from that point

**Comment by davidholsgrove** [comment]
No worries, thanks @JoelSpeed. Maybe a RC tagged release (and docker image) would be help?
