### ISSUE TITLE
Authorization header sent to upstream unconditionally

### ISSUE THREAD

**Issue by toote** [pusher/oauth2_proxy#205]
Currently have oauth2_proxy running off the `latest` tag with an nginx as an upstream that is configured as a proxy to ab AWS-managed ElasticSearch that authenticates via IP.

When trying to access Kibana through this setup, we get an error stating: `not a valid key=value pair (missing equal-sign) in Authorization header: 'Basic REDACTED'. `. 

## Current Behavior

After some debugging, it would appear that Oauth2_Proxy is passing through an `Authorization` to nginx in the request.

Documentation states that this should not be the case unless we use the option `-pass-authorization-header=true`. Unfortunately, that is not the case and ES can only be accessed after adding one of the following lines to the nginx configuration:

```
proxy_pass_request_headers off;
proxy_set_header  Authorization "";
```

I have also tried adding `-pass-authorization-header=false` to the command and the results are the same. Checking the developer console I can see that no `Authorization` header is sent from the browser nor there is any present in the response of `HOST/oauth2/auth`

## Expected Behavior

Authorization header should not be passed through to upstream as documented

## Steps to Reproduce (for bugs)

Running [`latest`](https://quay.io/repository/pusher/oauth2_proxy/manifest/sha256:1b136966dba1b222e45bab7b6da55b9b61b7ac1267937621c2221e4056e0e6ac) executing the following command:

```
oauth2_proxy \
   --upstream=http://nginx-container:8080/ \
   --http-address=0.0.0.0:8081 \
   -cookie-secret=64-char-long-string \
   -cookie-expire=24h0m0s \
   -footer=- \
   -provider=oidc \
   -email-domain=REDACTED \
   -client-id=REDACTED \
   -client-secret=REDACTED \
   -login-url=REDACTED \
   -profile-url=REDACTED \
   -redeem-url=REDACTED \
   -oidc-issuer-url=REDACTED
```

The Nginx container is setup quite simply with the following proxy configuration:

```
        location / {
            proxy_pass AWS-ELASTICSEARCH-DNS;
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  Host AWS-ELASTICSEARCH-DNS;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header  X-Forwarded-Proto $scheme;
       }
```

- Version used: [`latest`](https://quay.io/repository/pusher/oauth2_proxy/manifest/sha256:1b136966dba1b222e45bab7b6da55b9b61b7ac1267937621c2221e4056e0e6ac)

**Comment by ploxiln** [comment]
`--pass-basic-auth` defaults to True, you'll want to use `--pass-basic-auth=false`

**Comment by ploxiln** [comment]
(This `--pass-basic-auth` option sends just username, but no password, or a static password you configure separately, just as a way to pass username to some applications which may expect it this way. The `--pass-authorization-header` option sends Bearer with real token.)

**Comment by toote** [comment]
@ploxiln I will try that and let you know

**Comment by toote** [comment]
you were right... my bad for not reading the header correctly
