### ISSUE TITLE
Update email_domain documentation to show that it is a list/array.

### ISSUE THREAD

**Issue by Alives** [pusher/oauth2_proxy#207]
Documentation for Google provider does not list `email-domain` as a valid option.  I have a service that I want a Google account verified prior to accessing, but I do not care who the user is or what domain they are on.  Is this possible?

Setting `email_domain = "*" `in my conf resulted in:
```
main.go:120: Invalid configuration:
  missing setting for email validation: email-domain or authenticated-emails-file required.
      use email-domain=* to authorize all email addresses
```

**Comment by ploxiln** [comment]
try:
```
email_domains = ["*"]
```

**Comment by Alives** [comment]
Woohoo!  Can you update documentation to state the obvious, that this is a list?

**Comment by ploxiln** [comment]
There are a few different configuration options which are repeated-singular in the command-line flags, and a plural-list in the options file. So on the command line, this is still:

```
oauth2_proxy --email-domain="*"
```

**Comment by ploxiln** [comment]
(but if you find a good place to clarify, do open a pull request :)

**Comment by Alives** [comment]
I noticed that when using the config file, the only valid option is `email_domains`.  `email-domain`, `email-domains` are both invalid and result the error `use email-domain=* to authorize all email addresses` which is also inaccurate.  I think the singular/plural is misleading.  Is there a way to standardize config file / command args to all be the same?

Happy to open a PR, just need to figure out what the correct flag is...
