### ISSUE TITLE
Fails to start if `tls-cert-file` or `tls-key-file` not specified

### ISSUE THREAD

**Issue by toote** [pusher/oauth2_proxy#212]
I am testing OAuth2_Proxy using `latest` tag, a deployment that was running correctly with image `3426ecb` fails to start when using image `d1e37d3` with the error:

```
2019/07/15 22:58:31 ERROR: flag "tls-cert-file" does not exist
```

## Expected Behavior

Service should still start when not passing `tls-cert-file` options

## Current Behavior

Service doesn't start :(

## Possible Solution

Apparently, PR #186 forgot to update the [name of the options in `main.go`](https://github.com/pusher/oauth2_proxy/blob/630db3769bb5672f7dfbda52417d17f8ef198be2/main.go#L35)... but I am not well-versed in go to confirm that that is the complete extent of the issue

**Comment by JoelSpeed** [comment]
The highlighted solution is indeed the issue, apologies for missing this in #186. I'll raise a PR to fix tomorrow when I'm back at work

**Comment by andrevdh** [comment]
Hi @JoelSpeed we're also affected by this bug now ... and v3.2.0-arm64 is too old to roll back to (I think) for us

**Comment by JoelSpeed** [comment]
Please see #213 for the fix, will get merged shortly
