### ISSUE TITLE
getting code back but not access token, _oauth2_proxy cookie is also not set

### ISSUE THREAD

**Issue by fnaeem78** [pusher/oauth2_proxy#218]
I am running oauth_proxy release 3.2.0, darwin on my Macbook.  Here is my configuration 
The provider is azure. 

```
./oauth2_proxy-darwin-amd64  --provider=azure --client-id=<CLIENT_ID> --client-secret=<CLIENT_SECRET> --email-domain=* --cookie-secret=ThisisARandomString123456 -azure-tenant=<AZURE_TENANT_ID> --redirect-url=http://localhost:4180/login/oauth2/code/azure -resource=<OBJECT_ID_OF_RESOURCE>
--cookie-domain=*
```

## Expected Behavior

I was hoping to see both access_token and id_token but I am only seeing the code. 

## Current Behavior

Here is what I am getting 
```
127.0.0.1 - - [19/Jul/2019:15:46:28 -0500] localhost:4180 GET - "/login/oauth2/code/azure?code=AQABAAIAAAAP0wLlqdLVToOpA4kwzSnxtI0yhB98Wv78gVvza6tpK3-faojoHSdapNtp4mcC-J01P1mAyOk3rvZMWPTM7IWhvGq3ACQSyIA4bN4tPAfj6CSiHIvrvbQhT_QxrjAaCvwiTCJbex1d7NXtsKZVIRiGR8pzKABnqsqpzjtj5z2lgcSlea-EG2gSSKHi9QzhbeYg3GCu_BO8NGe4zztikeHACf4nhji6PMBDkaet5Tss_Opmlc4N5KqzzCSr-Fz_lLgLQtaa_vaawZNi1tXUhUUeE-4-x_fYB6WLGtPp34w0DhCWTma35YM2G3D0M-esq8NnSXGvMHq650KxzSBagrG06wHn1AObyMjxXDeddj9E351tAHmiOyxMg_qszYeZaglh4C5U_zm0VqFuUqGoaIOyzKJL-aAVy80iOipI5qb3lxbojvldnoxMBkCfrVsSuHV21V6v-NZg0BKwYLwEgkWnk7X5HNAc0C5ku7KIbjAW5dWhmA1cIy1wL8cicQ4Nxz5miDHkOua3Ce7iSdyUmVABGEise9AkpIxj0Vvd4XPRMiAA&state=a7c4520e0197a8e794d08ac9499ba29b%3a%2f&session_state=994faffc-0be1-4dcc-9eae-50b66298ff1e" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36" 403 3171 0.000
2019/07/19 15:46:28 oauthproxy.go:830: 127.0.0.1:52462 Cookie "_oauth2_proxy" not present
```
Why is the cookie not set, I looked through #26, but the suggestion there was to set the cookie domain.  Mine is already set to *.  I have also tried it without the cookie-domain but to no avail. 

If I look at the request in dev_tools, this is what I see. 
```
https://login.microsoftonline.com/<TENANT_ID>/oauth2/authorize?approval_prompt=force&client_id=<CLIENT_ID>&redirect_uri=http%3A%2F%2Flocalhost%3A4180%2Flogin%2Foauth2%2Fcode%2Fazure&response_type=code&scope=openid&state=e70b800d5a08602a872f7e9c7914c47e%3A%2F
```

## Possible Solution
For both V1 and V2 of Azure OIDC protocol, The following are mentioned 

https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-openid-connect-code#send-the-sign-in-request
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-the-sign-in-request

The request from dev_tools doesnt show id_token as a response_type nor is there a use of a nonce.

Is there a way to specify id_token, instead-of/in-addition-to code as a response_type. I looked through the config and didnt see anything. Also didnt see any option of saying nonce=true for it to use one. 

I am not sure if this is the source of my error or if I am making some other mistke. 

## Context
I am trying to see if I can get the access_token and some credentials, on stdout, and then I can configure upstream applications. I am trying to offload the whole oidc flow onto the oauth_proxy application. 

## Your Environment

- Version used:
OAuth 3.2.0 darwin os binary. 
MacOS X Mojave.

**Comment by steakunderscore** [comment]
At a glance, `_oauth2_proxy` cookie is not set because the secure flag is set on cookies by default. If you are testing with http, you'll need to add `--cookie-secure=false`. Let me know if this solves your issue?

**Comment by wallcrosstype** [comment]
If you're using provider=azure then you'll have to refer to 'authentication code' flow

- https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code
- https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

Alternatively you can set provider=oidc, issuer-oidc-url=https://login.microsoftonline.com/`tenant-id`/v2.0

---

    127.0.0.1 - - [19/Jul/2019:15:46:28 -0500] localhost:4180 GET - "/login/oauth2/code/azure?code=AQABAAIAAAAP0wLlqdLVToOpA4kwzSnxtI0yhB98Wv78gVvza6tpK3-faojoHSdapNtp4mcC-J01P1mAyOk3rvZMWPTM7IWhvGq3ACQSyIA4bN4tPAfj6CSiHIvrvbQhT_QxrjAaCvwiTCJbex1d7NXtsKZVIRiGR8pzKABnqsqpzjtj5z2lgcSlea-EG2gSSKHi9QzhbeYg3GCu_BO8NGe4zztikeHACf4nhji6PMBDkaet5Tss_Opmlc4N5KqzzCSr-Fz_lLgLQtaa_vaawZNi1tXUhUUeE-4-x_fYB6WLGtPp34w0DhCWTma35YM2G3D0M-esq8NnSXGvMHq650KxzSBagrG06wHn1AObyMjxXDeddj9E351tAHmiOyxMg_qszYeZaglh4C5U_zm0VqFuUqGoaIOyzKJL-aAVy80iOipI5qb3lxbojvldnoxMBkCfrVsSuHV21V6v-NZg0BKwYLwEgkWnk7X5HNAc0C5ku7KIbjAW5dWhmA1cIy1wL8cicQ4Nxz5miDHkOua3Ce7iSdyUmVABGEise9AkpIxj0Vvd4XPRMiAA&state=a7c4520e0197a8e794d08ac9499ba29b%3a%2f&session_state=994faffc-0be1-4dcc-9eae-50b66298ff1e" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36" 403 3171 0.000

this line mean that, at least, you're success in request an authorization code
refer to this step https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code#request-an-authorization-code
which end in 302 redirect to redirect-url?code=AwABAAAAvPM1KaPlrE

---

    2019/07/19 15:46:28 oauthproxy.go:830: 127.0.0.1:52462 Cookie "_oauth2_proxy" not present
This is nothing, not really error. This mention in log is just because authentication process not yet finished
You'll get Set-Cookie _oauth2_proxy when process finish

---

`code` in `/login/oauth2/code/azure?code=AQABAAIAAAAP0wLlqdLVToOpA4kwzSn`
will redeem for access token later
refer to https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code#use-the-authorization-code-to-request-an-access-token

**Comment by kjoth** [comment]
@fnaeem78  Did the issue got resolved? I'm also facing the same issue. It would be helpful to get inputs. 

BTW the I'm using Oauth2-proxy Helm charts, to install it. BTW is tenant ID is mandatory if I'm to use Azure.

**Comment by kjoth** [comment]
@steakunderscore , is there a Slack channel for oauth2-proxy project discussion?

**Comment by JoelSpeed** [comment]
Our slack is linked [here](https://github.com/oauth2-proxy/oauth2-proxy#getting-involved)

**Comment by hnaidin** [comment]
@kjoth @fnaeem78  did you solve the issue? i'm running into the same problem with the helm chart / oauth2-proxy binary

**Comment by kjoth** [comment]
@hnaidin , No I couldn't resolve the issue, actually it didn't seems to be issue "_auth cookie not set".  

Whats working:

It can able to get authenticated with Azure AD and giving back the token to the redirct Call back URL

Not Working/ Have to fix it:

The Callback URL. I don't know what should be the Call back URL. If I'm to use Jupyter Hub as redirct URL, then https:<domain>/hub/callback is giving 404 error.

Whats the issue you are facing? If its a _auth cookie not present, then its not an error it seems.

**Comment by hnaidin** [comment]
@kjoth check redirect-url [here](https://oauth2-proxy.github.io/oauth2-proxy/endpoints)
For me it looks like this: http://localhost:4180/oauth2/callback
Note: it has to be defined in your MS AD app.

**Comment by kjoth** [comment]
Then we have to expose the port 4180 via nodePort and use that port instead of 4180 in AD, i suppose. I will check and post the update. 

I'm not sure this below statement is right: Its not necessary for us to use only localhost:4180, we can use other call back urls like http://localhost:8888/hub/callback?
