### ISSUE TITLE
Support for GitLab groups

### ISSUE THREAD

**Issue by sc250024** [pusher/oauth2_proxy#228]
Opening issue for supporting GitLab groups, so that if using the `gitlab` provider, it's possible to limit authentication to only members of your group / organization.

## Expected Behavior

The GitLab provider should have something similar to the GitHub provider like so:

```
  -github-org string
    	restrict logins to members of this organisation
  -github-team string
    	restrict logins to members of this team
```

## Current Behavior

Currently, the GitLab provider only supports a very basic OAuth2 integration, which is that everyone with an account in that GitLab instance (whether it's self-hosted, or their SaaS offering) can authenticate with some proxied backend.

## Possible Solution

This should be possible since Grafana has support for groups with their GitLab OAuth integration => https://grafana.com/docs/auth/gitlab/

## Steps to Reproduce (for bugs)

N/A

## Context

N/A

## Your Environment

- Version used: **v3.2.0**

**Comment by JoelSpeed** [comment]
There was some work done around this but it never got merged, perhaps someone could pick it up again? https://github.com/pusher/oauth2_proxy/pull/137

**Comment by Overv** [comment]
I've been working on a similar PR, but I'd like to implement it differently than #137 so that it only requires the `openid` scope and not the whole `api`.

**Comment by sc250024** [comment]
@JoelSpeed thanks for the suggestion.

@Overv I was going to take the code JoelSpeed had suggested, and modify it to get it merged. If you don't have time I can work on it, but I don't know how much progress you've made.

**Comment by Overv** [comment]
@sc250024 I'm pretty far along and will be submitting a PR early next week.

**Comment by sc250024** [comment]
@Overv Oh cool! Honestly, I spun up this issue to remind myself to do it soon, but if you've already done it, that's awesome. Thank you so much!

**Comment by sc250024** [comment]
Closing since https://github.com/pusher/oauth2_proxy/pull/231 was merged! Thanks to @Overv !
