### ISSUE TITLE
Is there a way to authenticate from server side apps

### ISSUE THREAD

**Issue by omeryesil** [pusher/oauth2_proxy#230]
Is there a way to provide credentials and get the auth cookie without seeing the provider's login page which requires user interaction. 

We do have some backend code (desktop app, postman test scripts, etc..) which need to get authorized in order to call our apis running behind K8s Ingres with oauth2_proxy. It would be nice to have an option to send credentials from a backend code to get authorization cookie that we can make calls to the APIs.

**Comment by thangbn** [comment]
looking for this as well

**Comment by tatroc** [comment]
I am looking for this as well

**Comment by JoelSpeed** [comment]
Hey @omeryesil, could you provide a few extra details to help us work this out with you? 

Which provider are you using? 
Have you managed to get an ID Token for your backend code?
Have you seen the work done in #65? (Apologies it isn't really documented)

I believe the work from #65 may solve your issue, it was originally discussed in #18
