### ISSUE TITLE
docs(contributing): remove dep references

### ISSUE THREAD

**Issue by ferhatelmas** [pusher/oauth2_proxy#243]
## Expected Behavior

No mention of dep in contributing since modules are in use now.

Related, `GOPATH` requirement isn't valid either.

## Current Behavior

Install dependencies via dep.

## Possible Solution

Remove references to dep.

## Steps to Reproduce (for bugs)

N/A

## Context

https://github.com/pusher/oauth2_proxy/blob/master/CONTRIBUTING.md

## Your Environment

N/A

**Comment by syscll** [comment]
Fixed by #277
