### ISSUE TITLE
Incorrect sha256sum checksum file

### ISSUE THREAD

**Issue by sbocinec** [pusher/oauth2_proxy#251]
Current oauth2_proxy [sha256sum checksum file](https://github.com/pusher/oauth2_proxy/releases/download/v4.0.0/oauth2_proxy-v4.0.0.linux-amd64-sha256sum.txt) contains path that differs from the structure of the [release tarball](https://github.com/pusher/oauth2_proxy/releases/download/v4.0.0/oauth2_proxy-v4.0.0.linux-amd64.go1.12.1.tar.gz). This results in the checksum verification failure.

## Expected Behavior

1. Following the steps in the [Installation documentatio](https://pusher.github.io/oauth2_proxy/installation#installation) should result in successful binary checksum verification.

## Current Behavior

Checksum verification fails:

```
$ sha256sum -c oauth2_proxy-v4.0.0.linux-amd64-sha256sum.txt 
sha256sum: can't open 'release/oauth2_proxy-v4.0.0.linux-amd64.go1.12.1/oauth2_proxy': No such file or directory
release/oauth2_proxy-v4.0.0.linux-amd64.go1.12.1/oauth2_proxy: FAILED
sha256sum: WARNING: 1 of 1 computed checksums did NOT match
```

The structure of the release tarball:
```
$ tar xvf oauth2_proxy-v4.0.0.linux-amd64.go1.12.1.tar.gz 
oauth2_proxy-v4.0.0.linux-amd64.go1.12.1/
oauth2_proxy-v4.0.0.linux-amd64.go1.12.1/oauth2_proxy
```

## Possible Solution

Create the checksum file that match the directory structure of the released tarball:
* `oauth2_proxy-v4.0.0.linux-amd64.go1.12.1/oauth2_proxy` instead of  `release/oauth2_proxy-v4.0.0.linux-amd64.go1.12.1/oauth2_proxy`

## Steps to Reproduce (for bugs)
1. Follow the steps in the [Installation documentation](https://pusher.github.io/oauth2_proxy/installation#installation) for downloading latest v4.0.0 release
2. sha256sum verification fails

## Your Environment

- Version used: [v4.0.0](https://github.com/pusher/oauth2_proxy/releases/tag/v4.0.0)
- Tested with linuxamd64 artifacts: 
  * https://github.com/pusher/oauth2_proxy/releases/download/v4.0.0/oauth2_proxy-v4.0.0.linux-amd64.go1.12.1.tar.gz
  * https://github.com/pusher/oauth2_proxy/releases/download/v4.0.0/oauth2_proxy-v4.0.0.linux-amd64-sha256sum.txt

**Comment by syscll** [comment]
Thanks for bringing this to our attention!

After looking through some of the dist scripts, it looks like they haven't been migrated since we took over from [bitly/oauth2_proxy](https://github.com/bitly/oauth2_proxy).

I'll look into getting this fixed asap.

**Comment by syscll** [comment]
@JoelSpeed we should discuss this on Slack.

**Comment by syscll** [comment]
@sbocinec I have rewrote the dist scripts to fix this issue. Hope it helps :+1:

**Comment by sbocinec** [comment]
@syscll perfect, thank you for fixing this :+1:
