### ISSUE TITLE
Wrong environment variables handling

### ISSUE THREAD

**Issue by sbocinec** [pusher/oauth2_proxy#253]
The app incorrectly handles specified environment variables. For example setting OAUTH2_PROXY_EMAIL_DOMAIN is completely ignored and the app fails to start with error:
```
/ $ OAUTH2_PROXY_CLIENT_ID=foo OAUTH2_PROXY_CLIENT_SECRET=bar OAUTH2_PROXY_COOKIE_SECRET=true OAUTH2_PROXY_EMAIL_DOMAIN=test.example.org oauth2_proxy
[2019/08/22 19:52:49] [main.go:153] Invalid configuration:
  missing setting for email validation: email-domain or authenticated-emails-file required.
      use email-domain=* to authorize all email addresses
/ $ oauth2_proxy -version
oauth2_proxy v4.0.0 (built with go1.12.9)
/ $ cat /etc/alpine-release 
3.10.1
```

According to [documentation](https://pusher.github.io/oauth2_proxy/docs/configuration#environment-variables) "Every command line argument can be specified as an environment variable by prefixing it with `OAUTH2_PROXY_`, capitalising it, and replacing hypens (-) with underscores (_). This is particularly useful for storing secrets outside of a configuration file or the command line."

The `-email-domain` argument should be set by setting the `OAUTH2_PROXY_EMAIL_DOMAIN` environment variable.

## Expected Behavior

1. set `OAUTH2_PROXY_EMAIL_DOMAIN` environment variable to activate `-email-domain` argument: `export OAUTH2_PROXY_EMAIL_DOMAIN=example.org`

2. Run `oauth2_proxy` binary
3. App should not fail with following `Invalid configuration` error:
```
  missing setting for email validation: email-domain or authenticated-emails-file required.
      use email-domain=* to authorize all email addresses
```

## Current Behavior

```
/ $ export OAUTH2_PROXY_EMAIL_DOMAIN=example.org
/ $ oauth2_proxy 
[2019/08/22 19:55:42] [main.go:153] Invalid configuration:
  missing setting: cookie-secret
  missing setting: client-id
  missing setting: client-secret
  missing setting for email validation: email-domain or authenticated-emails-file required.
      use email-domain=* to authorize all email addresses
```

Note: There may be other command line arguments/variable affected (`-upstream`, `-whitelist-domain`, ...).

## Possible Solution

Looking on the code i found a workaround, setting the `OAUTH2_PROXY_EMAIL_DOMAINS` variable (notice the additional `S`), as the related code (`main.go:56`) set the `&emailDomains` var:
`flagSet.Var(&emailDomains, "email-domain", "authenticate emails with the specified domain (may be given multiple times). Use * to authenticate any email")`

Using the 'plural' version of the env variable helps to workaround this bug:
```
/ $ export OAUTH2_PROXY_EMAIL_DOMAINS=example.org
/ $ oauth2_proxy 
[2019/08/22 19:59:29] [main.go:153] Invalid configuration:
  missing setting: cookie-secret
  missing setting: client-id
  missing setting: client-secret
```

I think 2da89f842569ee0cd631bbd006cfa511bc82e018 introduced the error.

## Steps to Reproduce (for bugs)
```
/ $ export OAUTH2_PROXY_EMAIL_DOMAIN=example.org
/ $ oauth2_proxy 
[2019/08/22 19:55:42] [main.go:153] Invalid configuration:
  missing setting: cookie-secret
  missing setting: client-id
  missing setting: client-secret
  missing setting for email validation: email-domain or authenticated-emails-file required.
      use email-domain=* to authorize all email addresses
```

Note: There may be other command line arguments/variable affected by this buggy behaviour (`-upstream`, `-whitelist-domain`, ...).

## Context

Running a docker image only using env variables.

## Your Environment

- Version used: `v4.0.0`, `v3.2.0`
- OS: Alpine Linux, `quay.io/pusher/oauth2_proxy:v3.2.0`, `quay.io/pusher/oauth2_proxy:v4.0.0` docker images

**Comment by sbocinec** [comment]
OK, i found that according to the code using plural version of the env variable(s) is expected behaviour:
```
$ grep -R OAUTH2_PROXY_EMAIL_DOMAINS .
./options.go:	EmailDomains             []string `flag:"email-domain" cfg:"email_domains" env:"OAUTH2_PROXY_EMAIL_DOMAINS"
```

There are few others, like `OAUTH2_PROXY_EMAIL_UPSTREAMS`, `OAUTH2_PROXY_WHITELIST_DOMAINS`, etc.

So either the documentation is incorrect and should be updated to contain mapping of the command line arguments to the ENV vars variant or the code should be updated to follow the documented rule.

**Comment by JoelSpeed** [comment]
This is being clarified slightly in #252 though I appreciate the docs around configuration need an overhaul. I'd like to do some research on how over projects handle this but I don't have any time on my hands at present

**Comment by JoelSpeed** [comment]
@sbocinec Are you happy to close this issue?

**Comment by sbocinec** [comment]
@JoelSpeed, yeah, it's now more clear as the doc has been updated! Closing this issue

**Comment by SSAR13** [comment]
missing setting: cookie-secret
  provider missing setting: client-id
  missing setting: client-secret or client-secret-file
  missing setting for email validation: email-domain or authenticated-emails-file required.
      use email-domain=* to authorize all email addresses

Please provide a solution for this error?
