### ISSUE TITLE
Break the fork relationship to bitly/oauth2_proxy

### ISSUE THREAD

**Issue by jtnord** [pusher/oauth2_proxy#28]
The repo is a fork of bitly repo which is bad for a few reasons.

1) you end up in an incorrect tree (if you follow the forks you end up at an outdate repo - the root of the tree should be this repo
2) forked repos are not searchable in github

2 is the most annoying as you can not use github search cabapility to quickly scan the repos.

## Expected Behavior

pusher/oauth2_proxy is the root repo and not a fork, I can search its codebase in githubs native search capabilities.

## Current Behavior

I can search the codebase.

## Possible Solution

1) contack github support and ask github to break the fork relationship (but keep the issues and PRs in tact)
2) clone the entire repo (including PR refs) copy the issues etc delete the repo and then recreate it.

Obviously 1 is pretty easy, non destructive and painless, 2 is a right PITA :)

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

- Version used:

**Comment by JoelSpeed** [comment]
I think this is probably the right thing to do but didn't want to do it initially as I wasn't quite sure of the implications. I've done a bit of research and spoken to some people @pusher and we are generally in favour of this (no one's said don't do it). Do you agree this is the right way to go @syscll? I'll look into getting it done if you agree

**Comment by syscll** [comment]
I absolutely agree that this is the correct way to go. I see that [bitly/oauth2_proxy](https://github.com/bitly/oauth2_proxy) has now been archived, too.

Not sure if we'll still need to give credit to the original creators in order to comply with the MIT license.

**Comment by JoelSpeed** [comment]
> Not sure if we'll still need to give credit to the original creators in order to comply with the MIT license.

We have this note in the Readme

>Note: This repository was forked from bitly/OAuth2_Proxy on 27/11/2018. Versions v3.0.0 and up are from this fork and will have diverged from any changes in the original fork. A list of changes can be seen in the CHANGELOG.

I think that's probably sufficient but I'm not 100% certain

**Comment by JoelSpeed** [comment]
I have submitted a request to break the link between the two repositories

**Comment by JoelSpeed** [comment]
That was quick! All done!
