### ISSUE TITLE
Documentation inconsistent for -skip-auth-regex environment configuration

### ISSUE THREAD

**Issue by colinjfw** [pusher/oauth2_proxy#284]
## Expected Behavior

The environment variable `OAUTH2_PROXY_SKIP_AUTH_REGEXS` should configure the `skip-auth-regex` command line option.

This is documented here: https://github.com/pusher/oauth2_proxy/blob/master/docs/configuration/configuration.md#environment-variables.

> If the argument can be specified multiple times, the environment variable should be plural (trailing S).

## Current Behavior

The environment variable `OAUTH2_PROXY_SKIP_AUTH_REGEX` actually configures the `skip-auth-regex` command line option. Note the lack of `S`

## Possible Solution

I think that potentially pushing a documentation update that just lists the cli options along with their cli and environment variable counterpart. Documentation would look something like this:

| Option | Env var | Type | Description | Default |
| ------ | ------ | ---- | ----------- | ------- |
| `-acr-values` | `ACR_VALUES` | string | optional, used by login.gov | `"http://idmanagement.gov/ns/assurance/loa/1"` |

## Context

We just had to peer through the source in `options.go` to find the configuration needed. Not a huge blocker at all.

## Your Environment

- Version used: V4.0.0
- Running in docker.

**Comment by colinjfw** [comment]
I'm very happy that pusher is actively maintaining this fork by the way 🎉 happy to work on any improvements here.

**Comment by JoelSpeed** [comment]
Any help clarifying these would be appreciated! 

I wonder if we could divide the option box into three rows within the configuration table, one for the flag, one for the config file option, and one for the regex? 

I'm a little wary of adding an extra column as the table is already too wide and has to scroll.

Would you have time to play a bit and see what might look best for adding the information to the configuration table?

**Comment by colinjfw** [comment]
@JoelSpeed do you have a method of autogenerating that table or is it just built by hand? I couldn't find any scripts for it.

Once I get that worked out I can probably just fiddle with hopefully the max-width on that page and maybe adjust some of the column widths to get it looking right.

Does this make sense?

**Comment by JoelSpeed** [comment]
@colinjfw Unfortunately no, no scripts to build it (though if you fancy building one that would be awesome!)

Everything you've said makes sense :)

**Comment by jaredvacanti** [comment]
The documentation is clear that environment variables and command line arguments can be used interchangeably and gives the method for switching between them -- does the same rule work for the configuration file?

Also, the scroll is a little wonky with the table being so long. You have to scroll to the bottom to scroll horizontally. Maybe just a button to expand the table would be helpful, too.

**Comment by JoelSpeed** [comment]
Config file options are lower case and with underscores instead of hyphens, you can see the tags on this struct which show the `cfg` tag as what should be represented in the config file
https://github.com/pusher/oauth2_proxy/blob/35f2ae9a36bc979feb2377b40611fe4dd3d0c75a/options.go#L31-L133
