### ISSUE TITLE
Not working for self-hosted gitlab

### ISSUE THREAD

**Issue by Richie765** [pusher/oauth2_proxy#290]
I've been using the proxy with GitHub a while and now wanted to move to a self-hosted GitLab. I'm using docker with the following env vars:
```
- OAUTH2_PROXY_PROVIDER=gitlab
- OAUTH2_PROXY_CLIENT_ID=xxx
- OAUTH2_PROXY_CLIENT_SECRET=xxx
- OAUTH2_PROXY_UPSTREAMS=http://upstream:80
- OAUTH2_PROXY_LOGIN_URL=https://gitlab.company.com/oauth/authorize
- OAUTH2_PROXY_REDEEM_URL=https://gitlab.company.com/oauth/token
- OAUTH2_PROXY_EMAIL_DOMAINS=gmail.com
- OAUTH2_PROXY_COOKIE_SECRET=xxx
- OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
- OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY=true
```

When logging on it redirects to "gitlab.com" instead of "gitlab.company.com". So it's not picking up the login-url.

When I comment out the provider line, it does go to the correct gitlab to login, but afterwards it will give an "internal error" and according to the logs it is trying to use the default GoogleProvider.

Any ideas?

**Comment by JoelSpeed** [comment]
Looks like you need to set the OIDC issuer URL to your gitlab address and then it might work, basing this off of the code here:
https://github.com/pusher/oauth2_proxy/blob/6b8d2bdcc3b5abd61e73001a682d28b1193d1e21/options.go#L425-L447

`oidcVerifier` is constructed 
https://github.com/pusher/oauth2_proxy/blob/6b8d2bdcc3b5abd61e73001a682d28b1193d1e21/options.go#L231-L269

Please let me know if that works and we can update the docs

**Comment by Richie765** [comment]
Great! Got it working now. I see it in the docu now as well, I don't know how I missed it before. Tnx!
