### ISSUE TITLE
Oauth2_proxy configure multiple client ids 

### ISSUE THREAD

**Issue by Bluston** [pusher/oauth2_proxy#293]
One application has one client id and client secret.if i have some apps,can a oauth2_proxy configure multiple applications?

**Comment by JoelSpeed** [comment]
You could configure the OAuth2 Proxy using a whitelist domain to protect multiple apps (this is usually used in the nginx auth request mode), though the upstream identity provider would see only one client id and client secret

There is currently no support for multiple client ids and client secrets
