### ISSUE TITLE
Redirect URL missing when the skip-provider-button option is used

### ISSUE THREAD

**Issue by christidis** [pusher/oauth2_proxy#30]
When I use `-skip-provider-button=true` it always gets redirected after login to `/`
When I don't ( `-skip-provider-button=false`) it gets redirected after login to the url beforehand.

## Expected Behavior
preserve URL after the login regardless of the value of `-skip-provider-button` option.

## Steps to Reproduce (for bugs)
e.g. I point my browser at https://my-site/some/sub/path
when I have -skip-provider-button, it will end up pointing at https://my-site/
when I don't it will end up pointing at https://my-site/some/sub/path

## Your Environment
- Version used:
3.0.0

-----
Similar issues in bitly's archived repo:
https://github.com/bitly/oauth2_proxy/issues/327
https://github.com/bitly/oauth2_proxy/issues/586

**Comment by JoelSpeed** [comment]
I believe this may have been fixed in #24 which was merged earlier today, would you be able to test the current master build with the flag set to true?

**Comment by christidis** [comment]
Hm, I have just given `quay.io/pusher/oauth2_proxy` `latest` and `master` tags a try but noticed the same thing. URL is not preserved when `-skip-provider-button=true` is set.

**Comment by JoelSpeed** [comment]
In which case this will need further investigation

**Comment by rmoriz** [comment]
there is a PR at https://github.com/bitly/oauth2_proxy/pull/395

**Comment by framillien** [comment]
Hello, migrating from 3.0 to 3.1 fix this issue for me. I have removed option "-skip-provider-button", since original URL was not respected.

But this is now fixed in last version. Looking at code, it's the expected fix : take redirect from URL instead of unpopulated "rd" parameter (since "rd" is populated by skipped page)

Thanks,

**Comment by benley** [comment]
It appears that this is still not fixed in 3.2.0 or master.  Has someone opened a new PR to replace bitly/oauth2_proxy#395 and fix this, or is there another fix pending, or something else?
