### ISSUE TITLE
feature request - KeyWord args for provider endpoints

### ISSUE THREAD

**Issue by PaulCharlton** [pusher/oauth2_proxy#303]
I will be providing a PR for this.

some OAuth2 providers support a number of keywords not currently supported by oauth2_proxy.  

See for example: https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code#request-an-authorization-code and https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code for Azure Active Directory endpoints.  (specific nice to haves are "prompt", "domain_hint", "login_hint")

## Expected Behavior

Provider specific keywords and values should be supported in an extensible manner that does not require recompiling the oauth2_proxy.

## Possible Solution

add to `options.go`:
```
	ProviderTokenKVPairs                  []string `flag:"provider-token-kv-pairs" cfg:"provider_token_kv_pairs" env:"OAUTH2_PROXY_ PROVIDER_TOKEN_KV_PAIRS"`
```
and ensure that each KV pair is added to the provider's authorization and token refresh endpoints.

Nice to have:  Flag/Option/Env values allowed to be JSON strings or YAML format with "<(here_file)" or similar shell invocation.

## Context

OAuth providers have extended their offerings by make non-standard (non-RFC) keywords and values available.  This, or similar change, is needed to fully support integration with those providers.

**Comment by JoelSpeed** [comment]
I believe this can be achieved already by just providing the URLs by flag, though I admit this does defeat the point of OIDC discovery
```
--redeem-url=https://login.microsoftonline.com/{tenant}/oauth2/authorize?
client_id=6731de76-14a6-49ae-97bc-6eba6914391e
&response_type=code
&redirect_uri=http%3A%2F%2Flocalhost%3A12345
&response_mode=query
&resource=https%3A%2F%2Fservice.contoso.com%2F
&state=12345
```
