### ISSUE TITLE
Azure provider: Unexpected "Email" text comes up after authentication in Cookie value

### ISSUE THREAD

**Issue by aksrocks2015** [pusher/oauth2_proxy#310]
I am using oauth2_proxy behind Kubernetes ingress nginx to allow users of the cluster to access resources behind it.
Pretty much everything seems to work well (e.g., the authentication bearer token is correctly forwarded). But when the user comes back with {"Email":"xyz@abc.com"}, the program reads it from cookie the user id as "Email":"xyz@abc.com" obviously that is not correct. 
---------------------
2019-11-05 [http-xx-xx] INFO authenticationSe------ - Authentication : OAuth Cookie value = {"Email" : "xyz@abc.com"}
------------------------------
@JoelSpeed - Can you please advise. 

I'm using the annotation in the consuming service yml file.
----------
nginx.ingress.kubernetes.io/auth-signin:
nginx.ingress.kubernetes.io/auth-url:
nginx.ingress.kubernetes.io/auth-response-headers:
----------
I'm using below config in oauth yml file
---------------
provider = azure
azure-tenant = xxxxxx

env:
OAUTH_PROXY_CLIENT_ID
OAUTH_PROXY_CLIENT_SECRET
---------------
Do I need to use oauth-proxy_cookie_secret to just ensure I get value?

**Comment by epasham** [comment]
yes, use oauth-proxy_cookie_secret
