### ISSUE TITLE
Redirected path after signout is hardcoded to `/`

### ISSUE THREAD

**Issue by morarucostel** [pusher/oauth2_proxy#311]
After invoking the `sign_out` endpoint, the oauth2_proxy is redirecting to `/` which is hardcoded into the oauthproxy.go , you can see it [here](https://github.com/pusher/oauth2_proxy/blob/master/oauthproxy.go#L608).

When installed multiple instances of oauth-proxy in the same k8s cluster, for example one instance for app1 and a second one for app2, after the `sign_out`, the request will get redirected to the same endpoint without the possibility to differenciate among the two paths.

## Expected Behavior

The redirect path (after `sign_out`) should be configured in the oauth_proxy configuration as a parameter value. If left empy, the redirect should be defaulted to `/` as it is now.

## Current Behavior

Multiple instances of the `oauth_proxy` on the same k8s cluster will redirect to `/` whitout any way of configuring the redirected path to something more meaningful for the applications. 

## Possible Solution

Expose the redirect path as oauth-proxy configuration parameter under `-sign-out-redirect-path` to allow customisation of the redirected flow. If left empty, then the redirected path should be defaulted to `/` as it is now.
In addition we also need to update the documentation, in the endpoint section [here](https://pusher.github.io/oauth2_proxy/endpoints) the sign_out is missing.

## Steps to Reproduce (for bugs)

na

## Context

Unable to redirect the flow after sign_out to a relevant application path.

## Your Environment

- Version used: 3.1.0 and 4.0.0

**Comment by morarucostel** [comment]
@JoelSpeed 
If you are OK with the proposed solution I can for sure create a PR with the changes.

**Comment by JoelSpeed** [comment]
Hey @morarucostel, the `sign_in` path uses either a query parameter `rd` or header `X-Auth-Request-Redirect` for this purpose, I think we should try and maintain similar behaviour if possible, would that work for your use case? 

This method extracts it from the request so could be reused
https://github.com/pusher/oauth2_proxy/blob/9f920b0fc151ffdc057540c7dfdc87c612a2f8e7/oauthproxy.go#L478-L498

**Comment by morarucostel** [comment]
Hey @JoelSpeed , yes, your proposed solution will work in our case. 
I will push a PR with the modified `sign_out` method that maintain the similar behaviour like in `sign_in`.

**Comment by morarucostel** [comment]
Closed by the #314 .
@JoelSpeed thanks for the quick reply and merge.
