### ISSUE TITLE
Authenticate to oauth2_proxy Non-interactive

### ISSUE THREAD

**Issue by zarkoc** [pusher/oauth2_proxy#315]
## Expected Behavior
Hi All, Im trying to use a service principal to authenticate to Azure Non-interactively with presenting the Bearer token to the oauth2_proxy to login. Oauth2_proxy is deployed on kubernetes on Azure with nginx_ingress. 

When I do an interactive login, I open the app url from the browser, the app redirect me to the https://login.microsoftonline.com/ page where I enter my credentials and get sent back to the app.

## Current Behavior
When I try to do a non-interactive login.
1.  I do a POST to https://login.microsoftonline.com/tenant-id/oauth2/v2.0/token with the form-data:
client_id:xxxxxx
scope:https://app1.westeurope.cloudapp.azure.com/.default
client_secret:xxxxx
grant_type:client_credentials

As a response I get the Bearer token.

2. I try a GET https://app1.westeurope.cloudapp.azure.com/ with the Authorization header "Bearer tokenstring"
Currently when presenting the Bearer token via Postman I just get the Micrisoft login screen  https://login.microsoftonline.com/.

The relevant part of the oauth2_proxy cnfig

      - args:
        - --provider=azure
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --azure-tenant=xxxxx
        - --approval-prompt=none
        - --skip-provider-button=true
        - --scope=openid profile email
        env:
          - name: OAUTH2_PROXY_CLIENT_ID
            value: xxxxx
          - name: OAUTH2_PROXY_CLIENT_SECRET
            value: xxxxx
          - name: OAUTH2_PROXY_COOKIE_SECRET
            value: xxxxx

## Context

Is there a way to do a non-interactive login? We have an external app that needed to auth to a k8 app that is behind nignx_ingress with oauth2_proxy servring the authentification to Azure.

- Version used: 4.0.0 - also tried the latest and master branch.

**Comment by urbaniak** [comment]
Looking forward for similar functionality, wanted to secure api access with oauth2proxy with gitlab authentication and use `Authorization: Bearer <gitlab-user-token>`, but looks like it's not supported. 

Is it at possible to get it working like that? What needs to be developed in oauth2proxy? I'm happy to dig into, but wanted to make sure it's even possible.

**Comment by JoelSpeed** [comment]
You should be able to use the functionality added in #65 to achieve what you are trying.

Unfortunately, I don't think this is documented anywhere, if anyone has opportunity to add it to the docs, that would be greatly appreciated 😄

**Comment by fiammaz** [comment]
I recently implemented a solution similar to the one you need using Google as provider.
You have to start oauth2_proxy with:
```
-skip-jwt-bearer-tokens=true
-extra-jwt-issuers=https://accounts.google.com=$CLIENT_ID
```

extra-jwt-issuers MUST be specified even if you have already configured the same in oauth2_proxy.cfg

**Comment by JoelSpeed** [comment]
> extra-jwt-issuers MUST be specified even if you have already configured the same in oauth2_proxy.cfg

I think the intention was that specifying extra's shouldn't have been necessary, but perhaps that only works with the OIDC provider, perhaps that's something we should fix?

**Comment by fiammaz** [comment]
> I think the intention was that specifying extra's shouldn't have been necessary, but perhaps that only works with the OIDC provider, perhaps that's something we should fix?

I think so.
file: oauthproxy.go, line: 991

`	for _, verifier := range p.jwtBearerVerifiers {
		bearerToken, err := verifier.Verify(ctx, rawBearerToken)`

if extra-jwt-issuers is not set, p.jwtBearerVerifiers is null and the token isn't verified (returning a misleading error)

**Comment by fllaca** [comment]
This is ok if the access token is a JWT token, but when it's an opaque token the `-skip-jwt-bearer-tokens` cannot be used.
