### ISSUE TITLE
Redeeming a refresh token fails when the optional id_token is not in the response

### ISSUE THREAD

**Issue by howzat** [pusher/oauth2_proxy#318]
Expected Behaviour
--
When the Access Token expires, a Client can obtain a new Token by using their Refresh Token in conjunction with the Token Endpoint. 

According to the [relevant section of the OIDC specification](https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse) the **id_token** is optional within the response.

Given the attempt to refresh the Access Token is successful, but the Token Response doesn't include an **id_token**, the creation of new session state should succeed; updating the session with the new access token (and refresh token if provided) .

## Current Behaviour

Using the default oidc.go implementation, attempts to refresh an Access Token will fail when issued against OIDC providers who do not provide an **id_token** as part of the Token Response. 

> removing session. error refreshing access token unable to redeem refresh token: unable to update session: token response did not contain an id_token

## Possible Solution

In the current implementation both Redeem and RefreshSessionIfNeeded result in calls to [createSessionState](https://github.com/pusher/oauth2_proxy/blob/ca0b8375da57b84e33b3869ae0c0024c35d17177/providers/oidc.go#L100) with the assumption that the Token Response is uniform. The spec tells us that the handling of the **id_token** can vary in the Refresh Token Response.

The behaviour I believe is closer to the spec might be similar to this: https://github.com/howzat/oauth2_proxy/commit/01a6b661801ba079b7fe98ee9d9cedf5359bb0fb

## Steps to Reproduce (for bugs)

It's not easy provide example tests for the OIDC provider without refactoring the code. The test case would be to mock a response that does not contain a refresh_token nor an id_token.

## Your Environment
Running k8s, deployed using v 1.1.0 of the helm chart: https://github.com/helm/charts/tree/master/stable/oauth2-proxy

Chart defaults to:
https://github.com/helm/charts/blob/master/stable/oauth2-proxy/values.yaml
repository: "quay.io/pusher/oauth2_proxy"
tag: "v4.0.0"

**Comment by JoelSpeed** [comment]
Hey @howzat, thanks for bringing this bug to our attention! I agree with your analysis of our code and your proposed solution, would you be able to create a PR with the fix?

Out of interest, which IDP are you using? Do they not update the ID Token on a refresh? I'm a little confused about why you wouldn't want to update the token, surely in refreshing it this modifies the `exp` claim of the ID token and you would want this to be updated? Could you explain an example use case perhaps?

Finally, please make sure that once refreshed, the session refresh timing on the OAuth2 proxy is still honoured, we need to make sure it's not being refreshed based on the old token time if that is out of date now (I think it uses the `CreatedAt` field of the session but worth a double check!)

**Comment by howzat** [comment]
Thanks @JoelSpeed - I'll see what I can do. The IDP is Ping. What you say makes sense. I'm afraid I can't offer any insight as to whether this is the default behaviour for Ping or whether it is the result of some intentional (or otherwise) customisation.
