### ISSUE TITLE
InvalidAuthenticationToken - Access token validation failure. Invalid audience.

### ISSUE THREAD

**Issue by dmasbb** [pusher/oauth2_proxy#320]
Hi, I'm trying to enable SSO for our Bitbucket Server with Azure AD.
Pusher runs in docker (:4180) on the same docker engine as Bitbucket (:7990/:7999; with MiniOrange as SSO Plugin).
Before getting to pusher there is an Ngxinx reverse proxy (:443) in front.

I used the configured Client ID, Client Secret etc. in Postman successfully to get a Bearer Token, The Azure AD login appeared, I logged in and received the Baerer Token.
Which I used to  get my user informations via https://graph.microsoft.com/beta/me. 
It all worked.

## Current Behavior
Now If I try it with pusher I always get the following log message:

[2019/12/05 08:21:18] [requests.go:25] 401 GET https://graph.microsoft.com/beta/me/ {
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token validation failure. Invalid audience.",
    "innerError": {
      "request-id": "9dd16760-31c6-4f33-97ee-51e39809aebd",
      "date": "2019-12-05T07:21:18"
    }  }  }
x.x.x.46 - - [2019/12/05 08:21:18] [AuthFailure] Invalid authentication via OAuth2: unauthorized
x.x.x.46 - - [2019/12/05 08:21:18] code-t.sbb.ch GET - "/oauth2/callback?code=<long_code>&state=<state>%3a%2foauth2%2fsign_in&session_state=<session_state>" HTTP/1.0 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"

As I see in the documentation the log entry should be something like:
{{client_ip}} {{username}} {{timestamp}}
But in the log entry above no username is provided.
So it breaks before even receiving a JWT Token in my opinion, am I correct?
Did anyone encounter the same behaviour?

I'm new to pusher, appreciate any kind of advice/inputs on this.

**Comment by JoelSpeed** [comment]
It looks like the authentication is failing during the key exchange with Azure. The key message here is the `invalid audience` part. `audience` should match the client ID so try to ensure that the client ID is being set correctly in the OAuth2 Proxy, not sure what else to recommend from the information given apart from potentially adding some more debug logging to the code and running a more verbose version to try and hunt down the issue! 

P.S. FYI, [Pusher](pusher.com) is a very different thing to this, we refer to this project as `OAuth2 Proxy` and it is a side project that our infrastructure team plus community members maintain with nothing to do with Pusher's products or business 😅

**Comment by dmasbb** [comment]
Hi @JoelSpeed 

First, thank you for your help and the correction on the project name. :-)
I set the client id and secret with the env variable OAUTH2_PROXY_CLIENT_ID.
But as you suggested, I'll try a more verbose mode. 

What I'm trying to do, is enabling Oauth2 for Bitbucket (web and git clones) without using Crowd.
Do you have any experience with that? Does this constellation even work:

nginx (:443; ssl) redirecting to oatuh2_proxy (:4180) and redirecting the token to the Oauth2 MiniOrange plugin on Bitbucket.

**Comment by dmasbb** [comment]
I was able to make it run.
The app registration wasn't configured correctly and also the nginx reverse proxy running on the same host as the oauth2_proxy had some misconfigurations.

**Comment by stovla** [comment]
Hi @dmasbb,

Can you please be more specific on the issue, what was incorrectly configured on Azure AD?

**Comment by dmasbb** [comment]
Hi @stovla 
It looks like you have to use the same Azure AD App credentials for both (MiniOrange Plugin and oauth2_proxy).
