### ISSUE TITLE
Additional email validation in v4.0.0 breaks our setup

### ISSUE THREAD

**Issue by jheidbrink** [pusher/oauth2_proxy#322]
## Context

We use oauth2_proxy to restrict service access to members of two Google groups. Those groups belong to different domains. There is no Google account that can list the members of both groups, so we deploy two oauth proxies with different values for the `-google-admin-email` parameter. Both oauth proxies share one cookie secret.

## Expected Behavior

All users are authenticated by Proxy1. Users of domain1 use Proxy1 for setting the cookie, and users of domain2 use Proxy2 for setting the cookie. Proxy1 accepts cookies issued by both Proxies, given that they use the same cookie secret.

## Current Behavior

Version 3.2.0 behaves as described.

With commit bd651df3c25c5e82eec093b5c7b5ef1067bbf489, an additional `p.provider.ValidateGroup(session.Email)` was introduced after validating the cookie. This call fails in our setup when users of domain2 are authenticated by Proxy1.

## Possible Solution

I'm not sure if this is a bug or working as intended. Basically the behaviour of the auth route was changed from "If you have a valid cookie, you can pass" to "if you have a valid cookie, we query the Google API to make sure you are a member of the right groups and if you are, you can pass".

**Comment by jheidbrink** [comment]
@brianv0

**Comment by brianv0** [comment]
In refreshing my memory with the PR - I believe this was an attempt to normalize logic that exists below in the same file as well as more completely address #141, so I think it's closer to "working as intended", especially with more providers having group validators. I'd like @JoelSpeed to weigh in.

**Comment by InspektorWarnebring** [comment]
BTW, I deployed a helloworld app behind an oauth proxy v3.2 and behind an oauth proxy v4.0 to measure the impact of querying the Google API on request duration, and found that the service behind oauth proxy v4.0 takes approximately 80ms more to answer requests than the one behind oauth proxy v3.2.

I was also able to hit Google's rate limiting by making 400 requests to the helloworld app using `curl` in a `for`-loop.

Taking both the performance penalty and the rate limiting into account, I think it would be nice to allow authentication without querying the Google API for each request. After all, this effectively rate-limits the services behind an oauth proxy.

**Comment by jheidbrink** [comment]
BTW, I deployed a helloworld app behind an oauth proxy v3.2 and behind an oauth proxy v4.0 to measure the impact of querying the Google API on request duration, and found that the service behind oauth proxy v4.0 takes approximately 80ms longer to answer than the one behind oauth proxy v3.2.

I was also able to hit Google's rate limiting by making 400 requests to the helloworld app using `curl` in a `for`-loop.

Taking both the performance penalty and the rate limiting into account, I think it would be nice to allow authentication without querying the Google API for each request. After all, this effectively rate-limits the services behind an oauth proxy.

**Comment by brianv0** [comment]
I'm slightly confused that this actually worked before. It was always checking the group:

https://github.com/pusher/oauth2_proxy/blob/v3.2.0/oauthproxy.go#L779

But it was only doing so on initialization on the callback, instead of every request.

The code I added has to do it every request because the session may be derived from a token (so callback never called), however I agree that in the Google provider there should be some caching on the group members lookup, and there's none now.

**Comment by jheidbrink** [comment]
It worked before because we have two separate oauth proxy instances, one for each domain. Users of domain1 would use Proxy1 to sign in (they are members of a group of domain1) and users of domain2 would use Proxy2 to sign in (they are members of a group of domain2). So the `OAuthCallback` function that already included the check before would be called in the right oauth proxy.

Our services all use Proxy1 to authenticate users. Given that Proxy1 and Proxy2 share a cookie secret, users that signed in with Proxy2 would also be sucessfully authenticated by Proxy1 as they have a valid cookie. Now that the `authenticate` function also checks the group, Proxy1 does not authenticate users that signed in with Proxy2 anymore (because they are not members of the group of domain1).

**Comment by brianv0** [comment]
ah I see. I suppose you could have a third proxy which didn't use a group enforcement/admin email - but you'd want to make sure that proxy's `/oauth2/start` (and possibly `/oauth2/sign_in`) endpoints were protected/blocked in some way so it could not be used for a login.

I think that it's maybe possible for `ValidateGroup` to be removed. Only the google provider implements it. If people are using JWTs from Google to authenticate to oauth2_proxy AND expecting group validation - that would break for them, but as you point out, there's an API rate limiting issue so maybe that's not likely being used.

**Comment by jheidbrink** [comment]
We actually found that with v4.0.0 we don't even need this dual proxy setup anymore. Since commit 7d910c0ae8eef5620fd6524a38521e953d1adb8e we can have one group in domain1 that contains members of domain1 and domain2 and let oauth2_proxy check for membership in that group.

I'm leaving this issue open anyway, so the idea of caching the group member lookup or removing `ValidateGroup` from `getAuthenticatedSession` can still be discussed here.
