### ISSUE TITLE
Does `configure` add value?

### ISSUE THREAD

**Issue by JoelSpeed** [pusher/oauth2_proxy#324]
Currently, to use the `Makefile` in the root of the project, you first have to run `./configure` which looks for certain applications and checks they are present on your machine. It then dumps a `.env` with the correct paths to these applications.

I'm not convinced this adds much value to the Makefile and would rather substitute a Makefile with some preflight checks instead, ie, bail from the make target if you are missing go for instance (with a nice message).

WDYT @steakunderscore @syscll?

**Comment by syscll** [comment]
This sounds good to me. The `./configure` file never seems to work as expected for me, so I'd agree that it would be nice to remove an additional bash script.
