### ISSUE TITLE
Detaching oauth2_proxy from a single commercial organisation

### ISSUE THREAD

**Issue by syscll** [pusher/oauth2_proxy#327]
Since adopting from [bitly/oauth2_proxy](https://github.com/bitly/oauth2_proxy), we (the maintainers) and all of the contributors (old and new) have worked solidly to revive this project, and we wouldn't have been able to do that without the help of Pusher.

Now, 12 months later, we think it is time to detach the project from a single commercial organisation and create a new, open-source home for the OAuth2 proxy.

**I propose that we follow suit of the majority of open-source projects and migrate to:** `oauth2-proxy/oauth2-proxy`.

Reasons for doing so:
- The project will no longer rely on members of a commercial organisation to manage access/permissions.
- Pusher was always seen as a temporary home to kickstart the project back to life.
- We are considering merging with another open-source project to unify the OAuth2 proxies.
- We are working towards donating this project to the CNCF.
- Similar name as before (swapping underscore for a hyphen) as to not cause confusion.

I would love to hear user's feedback on the above and am happy answer questions and take suggestions!

**Comment by alexellis** [comment]
First of all congratulations on what you've been able to achieve. I'm not a user of this project but I can see the value of it being in the ecosystem. 

This all sounds like a solid case for what you're proposing.

> Similar name as before (swapping underscore for a hyphen) as to not cause confusion.

This actually does seem like it would cause a lot of confusion though. Do you remember Logrus/logrus and the fallout? Have you considered a completely new name or adopting the name of the project you wish to merge with?

My only other question is who will have the burden of responsibility for this project in its new home? What helps prevent the project from becoming unmaintained again?

**Comment by syscll** [comment]
> This actually does seem like it would cause a lot of confusion though. Do you remember Logrus/logrus and the fallout? Have you considered a completely new name or adopting the name of the project you wish to merge with?

My thoughts behind swapping the underscore for a hyphen was the ease of getting a domain name/GitHub username. I do remember the fallout from the Logrus name change, but I don't _think_ that would be a problem here as this isn't a library. But maybe I'm missing something?

I feel like keeping the name the same/similar might cause less confusion compared to creating a completely new name. For example, searching for the project will probably continue to point users correct repo.

> My only other question is who will have the burden of responsibility for this project in its new home? What helps prevent the project from becoming unmaintained again?

I would say the current maintainers would be solely responsible for managing the project, and anyone else who wanted to help maintain would be welcome to do so.

As it stands, I don't _think_ Pusher as an organisation has much, if any, say in the project - @JoelSpeed just happens to work there. I suppose my only concern is losing access to the project and I don't think this would be a problem if it was ran as a separate org.

This is a completely new area to me and I want to say that I have absolutely no hostility toward Pusher.

**Comment by Crevil** [comment]
To me this is a natural move for many OSS projects especialy when preparing adoption in a foundation.
Flux recently moved from Weaveworks to fluxcd for many of the same reasons.

Regarding the name change I think the change proposed is subtle enough that search engines will follow along. But I’m a bit unsure on what the benefits of the change is?

**Comment by syscll** [comment]
Closing this as we are having discussions with other open-source projects about a plan going forward. Will share more updates when things become more solid.
