### ISSUE TITLE
Self signed certificates for auth provider

### ISSUE THREAD

**Issue by tsraza** [pusher/oauth2_proxy#336]
## Expected Behavior

It would be nice to be able to pass a path to the root certificate of the auth provider.  This would be useful for self-hosted gitlab instances, for example.

## Current Behavior

You have to build a custom docker image (no big deal) to make it work.

## Possible Solution

There is currently a flag for the redis root certificate (`redis-ca-path`).  Implement a similar flag (`provider-ca-path`) and associated http client for the auth provider.

## Context

Requiring a custom docker image adds more files and pipelines and complexity.  Moving the custom ca cert option to the base image would simplify everything.

Knowing how to update certificates in alpine linux should be decoupled from this feature.

## Your Environment

- Version used: latest

**Comment by JoelSpeed** [comment]
Happy to have this supported, seems like a reasonable feature to have! I'm sure I was talking to someone about this recently though 🤔 I can't find the issue at the moment though and there doesn't seem to be a PR open that's relevant

**Comment by povils** [comment]
I have the exact use case :)

**Comment by JoelSpeed** [comment]
I think there is a workaround for this by adding your self signed CA cert to your system roots, but I'd welcome a PR to implement this if anyone has the time

**Comment by paddy-hack** [comment]
Looks like issue #635 and PR #645 address this.
