### ISSUE TITLE
Support for Redis Cluster

### ISSUE THREAD

**Issue by yan-dblinf** [pusher/oauth2_proxy#340]
## Expected Behavior
As Redis Cluster is widely used in my company, we'd adopt it as the session store. 

## Current Behavior
Only Redis and Redis Sentinel are supported as #155.  

## Possible Solution
I made a workable [quick-patch](https://github.com/yan-dblinf/oauth2_proxy/commit/3c367af4d60b2ed0a3b1abf4fefff2cd1e54b87f) verified by our current use cases.  However, there are many duplications from copy-and-paste. It's good to merge the two session store types: redis and rediscluster. I'm willing to improve the solution with a PR if the feature is needed by the community and no duplicated effort has been started. 

## Your Environment

- Version used:
v4.1.0

**Comment by JoelSpeed** [comment]
When this was implemented, I didn't really expect people to need redis cluster. My understanding is that cluster is used when you need to shard data, and I didn't imagine the OAuth2 Proxy session storage to be that big? 

That said, this seems like a reasonable thing to support in addition to sentinel, though I'd ask if you could remain with one provider within the code base, maybe `--redis-use-cluster` flag could be added to tell the implementation to use cluster mode? WDYT?

**Comment by ploxiln** [comment]
looks like this was addressed in #363 and can be closed
