### ISSUE TITLE
Support for client secret file.

### ISSUE THREAD

**Issue by pasha-r** [pusher/oauth2_proxy#341]
## Expected Behavior

Some OAuth2 identity management systems rotate client secrets and upload such secrets to running applications as a file in a mounted volume. I would like to be able to read client secret from an in-memory file every time I need to issue a redeem or redeem refresh request.

## Current Behavior

Currently the value of ClientSecret is set for the lifetime of the application. Rotating a client secret will be very cumbersome in the current implementation.

## Possible Solution

Solution I have in mind is like this:
1. add client-secret-file option
2. make ProviderData's ClientSecret a function
3. if client-secret-file is set ClientSecret() reads the file an returns its context
4. if client-secret-file is not set ClientSecret() behaves the usual way
5. I replace all p.ClientSecret reads with p.ClientSecret() call

What do you think about this solution? Any holes, problems, alternative ideas?

**Comment by JoelSpeed** [comment]
>Some OAuth2 identity management systems rotate client secrets and upload such secrets to running applications as a file in a mounted volume.

I've not seen any OAuth2 systems that do this before, have you got a link to where I could learn more about this and how it works within one of these providers? 

Your solution seems very reasonable, I'm sure we'd happily accept a PR that implements the suggestion 😄

**Comment by pasha-r** [comment]
Thanks!
I'll create a PR. Hopefully next week 😄

About the secrets' management system. It's an internal system. But apparently it was open-sourced!
This: https://kubernetes-on-aws.readthedocs.io/en/latest/user-guide/example-credentials.html
And this: https://kubernetes-on-aws.readthedocs.io/en/latest/user-guide/zalando-iam.html

And it's also possible to rotate google IAM credentials for service accounts: https://cloud.google.com/iam/docs/creating-managing-service-account-keys#deleting_service_account_keys
The docs from Google don't provide a mechanism for automated delivery of the rotated secrets to running apps. But the idea is the same - either restart your app every time key is rotated or read it from somewhere every time you need the secret.

**Comment by pasha-r** [comment]
https://github.com/pusher/oauth2_proxy/pull/355

**Comment by JoelSpeed** [comment]
This is merged
