### ISSUE TITLE
Keycloak provider documentation

### ISSUE THREAD

**Issue by Jude188** [pusher/oauth2_proxy#343]
## Expected Behavior

At the moment the documentation around the Keycloak Provider does not mention the `-keycloak-group` argument. 
https://github.com/pusher/oauth2_proxy/blob/master/options.go#L45

## Current Behavior

It probably should as this is a very very useful feature for Keycloak users which the current OIDC provider does not support.

## Possible Solution

Add some more docs

**Comment by JoelSpeed** [comment]
Probably should be mentioned I agree! Has anyone got time to rustle up a PR?

**Comment by sushiMix** [comment]
I would add :

Replace in documentation 
-redeem-url="http(s)://<keycloak host>/realms/master/<your realm>/openid-connect/auth/token"
-validate-url="http(s)://<keycloak host>/realms/master/<your realm>/openid-connect/userinfo"
by 
-redeem-url="http(s)://<keycloak host>/realms/<your realm>/protocol/openid-connect/token"
-validate-url="http(s)://<keycloak host>/realms/<your realm>/protocol/openid-connect/userinfo"
to be exact.

It seems token claim name in Keycloak should be equals to -keycloak-group but not yet sure.
