### ISSUE TITLE
oauth2_proxy -  unable too obtain CSRF cookie

### ISSUE THREAD

**Issue by mike-sirs** [pusher/oauth2_proxy#360]
Unable too obtain CSRF cookie

Hi 
i'm trying to use **oauth2_proxy** with Gloo as a [сustom Auth server ](https://docs.solo.io/gloo/latest/security/auth/custom_auth/)

## Current Behavior

```
[2020/01/21 16:57:13] [oauthproxy.go:213] mapping path "/" => upstream "http://127.0.0.1:8080/"
[2020/01/21 16:57:13] [oauthproxy.go:259] OAuthProxy configured for Google Client ID: 647482553267-agjle5ngzbpu4o817qlbet7ig33rv0iq.apps.googleusercontent.com
[2020/01/21 16:57:13] [oauthproxy.go:265] Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domain: path:/ samesite: refresh:disabled
[2020/01/21 16:57:13] [http.go:92] HTTP: listening on 0.0.0.0:8080



[2020/01/21 16:57:33] [oauthproxy.go:850] Error loading cookied session: Cookie "_oauth2_proxy" not present
10.16.1.11 - - [2020/01/21 16:57:33] nexus.infra.gcp.projects.sirs.com GET - "/" HTTP/1.1 "" 403 2522 0.001
10.16.1.11 - - [2020/01/21 16:57:41] nexus.infra.gcp.projects.sirs.com GET - "/oauth2/start?rd=%2F" HTTP/1.1 "" 302 382 0.000
10.16.1.11 - mike_sirs@sirs.com [2020/01/21 16:57:44] [AuthFailure] Invalid authentication via OAuth2: unable too obtain CSRF cookie
10.16.1.11 - - [2020/01/21 16:57:43] nexus.infra.gcp.projects.sirs.com GET - "/oauth2/callback?state=6d017b30862c3e9d228dd320254a2049:/&code=4/vgE0CNKKHg6G8PfHFGj-lv_WQtSxKUrgMPUXbGNQwVMapYFaHupeUXpCvIsvpnMSWM0ge6X3NXT-_A4CCuOMstY&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=0&hd=sirs.com&prompt=consent&session_state=98a33ed74807ea5aed0b6da56683311dd143cff1..973d" HTTP/1.1 "" 403 353 0.147
```

## oauth2_proxy config
```
http_address = "0.0.0.0:8080"

provider = "google"
cookie_secure = true
cookie_secret = "secret-here"

email_domains = [
    "sirs.com"
]
pass_access_token = true
pass_authorization_header = true
skip_provider_button = false
set_authorization_header = true
set_xauthrequest = true
skip_auth_preflight = false

client_id = "id-here"
client_secret = "secret-here"
```
In chrome cookies I have _oauth2_proxy_csrf

I've tried solutions from existing issue reports like `"_oauth2_proxy" not present` but no luck. I'm missing something. 

i'm sure the issue is with gloo redirects

**Comment by mike-sirs** [comment]
So it works fine if i use it as a proxy)) and not just a auth server which suppose to respond 200OK if request is authorized to pass it further.
so config like below works fine
```
http_address = "0.0.0.0:8080"

provider = "google"
cookie_secure = true
cookie_secret = "kjsdlfjsdkjflsdjkf=="
whitelist_domain = ".infra.gcp.projects.sirs.com"
cookie_domain = "nexus.infra.gcp.projects.sirs.com"
email_domains = [
    "*"
]
redirect_url = "https://nexus.infra.gcp.projects.sirs.com/oauth2/callback"
pass_access_token = true
pass_authorization_header = true
skip_provider_button = false
set_authorization_header = true
set_xauthrequest = true
skip_auth_preflight = false

upstreams = [
    "http://nexus.applications.svc.cluster.local:8081"
]

client_id = "appid.apps.googleusercontent.com"
client_secret = "secret"
```

**Comment by dmahisingh** [comment]
Hi Mike,
I am using Azure provider and deployed in kubernetes. 
When I am using safari or any old browser, I am getting the same error ' **Invalid authentication via OAuth2: unable too obtain CSRF cookie** in the log and my browser shows - **403 Permission Denied http: named cookie not present**.
Please find my config files 
https://github.com/pusher/oauth2_proxy/files/4169075/oauth2_proxy.txt
https://github.com/pusher/oauth2_proxy/files/4169107/ingress.txt
Appreciate if you can light on this and any help/suggestions on the same

**Comment by ShyLionTjmn** [comment]
Got same error. Trying to use nginx auth_request and Keycloak

**Comment by olopost** [comment]
Hi, this issue come from csp policy applied by browser. For example, the behaviour not exist on chrome browsers.

This come from the enforcement on firefox and safari browser. We need to adapt content-security-policy parameter to adapt to your dns name for exchange with the name of your idp.

Best regards.

**Comment by flechaig** [comment]
Hi, I had a similar issue with Nginx in front as a reverse-proxy. The root cause was that the HTTP 302 redirect on the original request (not authenticated) was cached by the browser. So I had to add "expires epoch;" in nginx /oauth2 location to prevent caching of the redirect.

**Comment by rshiva777** [comment]
@olopost  @flechaig ,

I am getting the same issue in chrome browser as well. Could you pls help

![image](https://user-images.githubusercontent.com/42074614/210924574-f4cc5b4c-5add-42f1-abdb-85d4a425e35c.png)

**Comment by aleks-programmer** [comment]
Got the same issue when trying to use http instead of https
