### ISSUE TITLE
Support prompt in addition to auth-prompt

### ISSUE THREAD

**Issue by holyjak** [pusher/oauth2_proxy#380]
Support to send [OAuth v2 `prompt`](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#send-the-sign-in-request) instead the v1 `auth_prompt`. 

## Expected Behavior

Being able to include e.g. `&prompt=login` in the login-url and no `auth_prompt` (or neither of the two).

## Current Behavior

No way to set the `prompt` query parameter in the login URL.

## Possible Solution

Adding a new config option for `prompt` together with not sending `auth_prompt` if empty (provided by #316) would fix this.

## Context

I am using an Auth2 provider that expects the `prompt` request param.

## Your Environment

- Version used: 5

**Comment by nzoueidi** [comment]
cc'ing myself as I am having the same behaviour.
