### ISSUE TITLE
`acr_values` should be available for all providers

### ISSUE THREAD

**Issue by holyjak** [pusher/oauth2_proxy#381]
We use an OIDC provider that also accepts the `acr_values` parameter in the login URL but it is currently only enabled for the login.gov provider. It should be made available for all providers or at least for `oidc` (which we use) in addition to login.gov.

NOTE: It seems that [acr_values is a general OIDC thing](https://openid.net/specs/openid-connect-eap-acr-values-1_0.html).

## Expected Behavior

I expect to be able to set `acr_values` in the login URL when using an OIDC provider.

## Current Behavior

Not possible.

## Your Environment

- Version used: 5

**Comment by JoelSpeed** [comment]
This should be added. I wonder if there is a good way in which we can make additional properties like this available generically so that we don't keep adding specific code for little optional things like this
