### ISSUE TITLE
Fails to start with error flag "client-secret-file" does not exist

### ISSUE THREAD

**Issue by MisterWil** [pusher/oauth2_proxy#396]
After upgrading the docker image this morning my otherwise working instance fails to start with the error: flag "client-secret-file" does not exist

Seems this is related to #341 and #355 

```
2020/02/15 16:00:33 ERROR: flag "client-secret-file" does not exist
panic: ERROR: flag "client-secret-file" does not exist

goroutine 1 [running]:
log.Panicf(0xb6d3da, 0x1d, 0xc000233cc8, 0x1, 0x1)
/usr/local/go/src/log/log.go:345 +0xc0
github.com/mreiferson/go-options.Resolve(0xa74860, 0xc0000d7600, 0xc0000a5200, 0xc0000f74d0)
/go/pkg/mod/github.com/mreiferson/go-options@v0.0.0-20190302064952-20ba7d382d05/options.go:73 +0xb7b
main.main()
/go/src/github.com/pusher/oauth2_proxy/main.go:159 +0x1e13
```

## Expected Behavior

The lack of this config option shouldn't cause a complete failure to start.

## Steps to Reproduce (for bugs)

1. Don't configure  the 'client-secret-file' flag.
2. Start oauth2
3. Fails to start

## Your Environment

Docker image on unRaid OS.

- Version used: [latest docker image](https://quay.io/repository/pusher/oauth2_proxy/manifest/sha256:78f2205712887c5eff98e515c3a99f8f84db4ca6458042e1d4a9b32844427d6d)

**Comment by JoelSpeed** [comment]
This is a programming error, when #355 was implemented, it should have included a flag in the main file like this https://github.com/pusher/oauth2_proxy/blob/2033ce81c3a96e75eb73e92af648ea6ed5c02a6f/main.go#L72

@pasha-r or anyone else, do you have time to create a PR to fix this missing flag registration?

**Comment by dmahisingh** [comment]
My Oauth2 proxy is not working now with the same error - Please help on this, what should we do now?

**Comment by dmahisingh** [comment]
I was trying something else and restarted my oauth proxy and it stopped working with the same error - My application is stopped working now - Please suggest on this. 
Can I use the prev image to deploy my oauth2 proxy?

**Comment by Freebios** [comment]
@dmahisingh 
> I was trying something else and restarted my oauth proxy and it stopped working with the same error - My application is stopped working now - Please suggest on this.
> Can I use the prev image to deploy my oauth2 proxy?

Just use the previous release:
quay.io/pusher/oauth2_proxy:v4.1.0 instead of latest

**Comment by JoelSpeed** [comment]
Please use the latest release `v5.0.0` until this is resolved. There is an important security fix that was released with this version and using anything older will leave that vulnerability exposed
