### ISSUE TITLE
BitBucket support

### ISSUE THREAD

**Issue by shouptech** [pusher/oauth2_proxy#40]
I work for an org that uses BitBucket Cloud for all of our repos. It'd be nice if oauth2_proxy could be used w/ BitBucket.

## Expected Behavior

It'd be nice if oauth2_proxy has a BitBucket provider.

## Current Behavior

oauth2_proxy can't be used with BitBucket right now. BitBucket supports Oauth2, but not OpenID connect, so a new provider would be needed.

## Possible Solution

Add bitbucket as a provider? I'd be willing to spend some time writing a PR for this, but it may take me awhile and I lack confidence in my skills.

## Steps to Reproduce (for bugs)

N/A

## Context

The org I work for uses BitBucket cloud for all of our repos. I'd like to deploy various internal tools for developers to access and authorize them using their BitBucket credentials.

**Comment by JoelSpeed** [comment]
I don't see any reason why we couldn't support this. I don't personally have any way to test that a Bitbucket provider would work however so it would require someone to volunteer to keep it maintained and tested.

it may interest you to know that [Dex connects up to Bitbucket](https://github.com/dexidp/dex/blob/master/connector/bitbucketcloud/bitbucketcloud.go) so you could use Dex to translate Bitbucket to OIDC and use the OAuth2 Proxy with that.

**Comment by ploxiln** [comment]
https://github.com/bitly/oauth2_proxy/pull/385 may give a useful reference or starting point for a PR adding a bitbucket provider
