### ISSUE TITLE
Release links include .gz extension but files are not GZipped

### ISSUE THREAD

**Issue by rafaelmagu** [pusher/oauth2_proxy#42]
Links to the binaries in the 3.0.0 release include `.gz` extensions, when in fact the links are just TAR files.

## Expected Behavior

```bash
$ curl -sL https://github.com/pusher/oauth2_proxy/releases/download/v3.0.0/oauth2_proxy-v3.0.0-0-g7887272.linux-amd64.go1.11.tar.gz | tar zxvf -
release/oauth2_proxy-linux-amd64
```

## Current Behavior

```bash
$ curl -sL https://github.com/pusher/oauth2_proxy/releases/download/v3.0.0/oauth2_proxy-v3.0.0-0-g7887272.linux-amd64.go1.11.tar.gz | tar zxvf -

gzip: stdin: not in gzip format
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
```

## Possible Solution

Remove `.gz` from the links, or GZip the TAR files.

## Steps to Reproduce (for bugs)

1. Download one of the binaries.
2. Attempt to `gunzip` it.

## Context

```bash
$ file oauth2_proxy-v3.0.0-0-g7887272.linux-amd64.go1.11.tar.gz
oauth2_proxy-v3.0.0-0-g7887272.linux-amd64.go1.11.tar.gz: POSIX tar archive
```

## Your Environment

Ubuntu Linux 18.04.

**Comment by JoelSpeed** [comment]
Apologies, they were meant to be zipped. The problem will be in the `Makefile` `release` target, I'll double check it and fix. Thanks for bring this to our attention!
