### ISSUE TITLE
Issuer Name Mismatch

### ISSUE THREAD

**Issue by western24** [pusher/oauth2_proxy#449]
Hi,
I'm trying to use oauth2_proxy with Oracle Identity Cloud Service.  The following parameters are added in the configuration file as Open ID Connect. But  I'm faced with an error that the issuer didn't match. Probably, issuer value returned by Oracle IDCS is different from your expectations.  Can I avoid this error?

client_id = "xxxxxx"
client_secret = "xxxxxxx"
provider = "oidc"
oidc_issuer_url ="https://idcs-fd65079a19ab43ab808d264c927d3401.identity.oraclecloud.com"

sudo  /usr/local/sbin/oauth2_proxy -config /etc/oauth2_proxy.cfg
[2020/03/16 16:09:19] [main.go:160] oidc: issuer did not match the issuer returned by provider, expected "https://idcs-fd65079a19ab43ab808d264c927d3401.identity.oraclecloud.com" got "https://identity.oraclecloud.com/"

- Version used:
v5.0.0.

**Comment by JoelSpeed** [comment]
This issue is actually in a dependency of this project
https://github.com/coreos/go-oidc/blob/8d771559cf6e5111c9b9159810d0e4538e7cdc82/oidc.go#L140-L142
Would you open an issue there as well and link it back here? I'd be intrigued to see what they say

Normally the `oidc_issuer_url` would match the `issuer` field at the [discovery endpoint](https://idcs-fd65079a19ab43ab808d264c927d3401.identity.oraclecloud.com/.well-known/openid-configuration), I've not seen it not match like this before

**Comment by Morriz** [comment]
why was this closed @western24 ? I think we need a backchannel option for discovery...

@JoelSpeed is this already possible somehow?

**Comment by Morriz** [comment]
Maybe running 2 isntances sharing same storage could work...ugly

**Comment by JoelSpeed** [comment]
Have you tried either `--insecure-oidc-skip-issuer-verification` or just setting up all the endpoints manually by skipping discovery?

**Comment by Morriz** [comment]
The point is to allow internal as well as external urls. One option per endpoint does not cut it. Keycloak has an option to just return the well known URI based on the HOST header it receives. That way it works transparently.

**Comment by Morriz** [comment]
They do so by default and it needs to be locked to external URL explicitly.

**Comment by JoelSpeed** [comment]
Can you help explain the advantage of having support for both internal and external? What is the problem you are trying to solve here?

**Comment by pratiyushpushkar05** [comment]
I am facing this very issue ,
```ERROR: Failed to initialise OAuth2 Proxy: error intiailising provider: could not create provider data: error building OIDC ProviderVerifier: could not get verifier builder: error while discovery OIDC configuration: oidc: issuer did not match the issuer returned by provider```
Usinf Dex and Oauth2 . Can anyone let me know how to debug or where to set issuer url in provider ?
