### ISSUE TITLE
Inconsistent config file structure

### ISSUE THREAD

**Issue by swade1987** [pusher/oauth2_proxy#49]
## Expected Behavior

I would expect the following:

```
 ProxyPrefix  string `flag:"proxy-prefix" cfg:"proxy_prefix"` 
```

## Current Behavior

All other config options are `x_y` apart from proxy prefix, see https://github.com/pusher/oauth2_proxy/blob/402ce6f0cb3501486b959a0e629ba3ad810d390a/options.go#L24

## Your Environment

- Version used:

Master image

**Comment by JoelSpeed** [comment]
We should fix this as it is an easy fix, it would be good to find a way to do it in a backwards compatible way though, else we should bump to version 4. 

Shall have to have a think on that.

**Comment by swade1987** [comment]
I would propose a walkthrough of `flag` vs `cfg` as some are inconsistent such as:

https://github.com/pusher/oauth2_proxy/blob/402ce6f0cb3501486b959a0e629ba3ad810d390a/options.go#L36
