### ISSUE TITLE
oauth2_proxy stripping out content-length header?

### ISSUE THREAD

**Issue by Ghazgkull** [pusher/oauth2_proxy#72]
## Expected Behavior

When a request is proxied by oauth2_proxy, all headers are proxied to the upstream.

## Current Behavior

If I make an authenticated GET request with a `content-length: 0` header, the header is not sent to the upstream.

Interestingly, if I set tell oauth2_proxy to skip auth for the affected route (e.g. `skip-auth-regex: /api`), then the proxy *does* pass the headers through.

## Possible Solution

Is there anything I can do as a client to tell oauth2_proxy to pass along all headers to the upstream? Or is a code change needed?

## Context

In my particular case, this is a breaking issue. I'm proxying the Kibana dashboard behind oauth2_proxy and the XHR request it makes to fetch data fails with a 403 when the content-length header is missing.

## Your Environment

Running oauth2_proxy in a kubernetes pod behind an Istio ingress on AWS EKS.

* Version used:

3.1.0
docker image: https://quay.io/repository/pusher/oauth2_proxy?tag=v3.1.0

**Comment by ploxiln** [comment]
Most arbitrary headers are passed through. Content-Length is handled specially by the Go http client which is used by the Go reverse proxy. Here's the relevant bit:
https://golang.org/src/net/http/transfer.go#L260

For a `GET` request, `Content-Length: 0` is implied, and it considers it not needed.

**Comment by artyomtkachenko** [comment]
I am facing exactly the same issue with Kibana. @Ghazgkull  have you found any workaround for it?
--skip-auth-regex trick works fine for me, but I am looking for something more secure.

**Comment by Ghazgkull** [comment]
@artyomtkachenko Yeah, since it sounds like oauth2_proxy isn't usable as an actual proxy, I've gone the route of setting up a simple nginx deployment/service/configmap which I use as the actual proxy. oauth2_proxy is then configured only to perform authentication for the nginx service using the auth-request module as explained in the README.md of this repo.

It's working fine and now I'm just going through the process of figuring out how to package the pieces for reuse. I'm currently consuming oauth2_proxy via the stable helm chart. So I'm thinking I might be able to package everything up as a new chart which consumes the oauth2_proxy chart as a dependency (sub chart).

I'll post back here if I'm able to get such a thing packaged up. Totally new to helm though, so...

**Comment by Ghazgkull** [comment]
@artyomtkachenko In case it helps, here's where I'm at with my nginx.yaml. Notice that a couple parts are hard-coded to my setup currently. I'm running Kibana behind an istio gateway under the `/logs` route, which is why you'll see that path segment in the URLs. And the hostnames are specific to my k8s service names:

```
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-auth-proxy
  labels:
    app: nginx-auth-proxy
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nginx-auth-proxy

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-auth-proxy
  labels:
    app: nginx-auth-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-auth-proxy
  template:
    metadata:
      labels:
        app: nginx-auth-proxy
    spec:
      containers:
        - name: nginx-auth-proxy
          image: nginx
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: auth-proxy-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: auth-proxy.conf
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
      volumes:
        - name: auth-proxy-config
          configMap:
            name: nginx-auth-proxy-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-auth-proxy-config
data:
  auth-proxy.conf: |
    server {
      listen 80 default_server;
      server_name _;
      error_log /dev/stdout debug;
      access_log /dev/stdout;

      location /logs/oauth2 {
        proxy_pass       http://oauth2-proxy;
        proxy_set_header Host                    $host;
        proxy_set_header X-Real-IP               $remote_addr;
        proxy_set_header X-Scheme                $scheme;
        proxy_set_header X-Auth-Request-Redirect $request_uri;
      }
      location = /logs/oauth2/auth {
        proxy_pass       http://oauth2-proxy;
        proxy_set_header Host             $host;
        proxy_set_header X-Real-IP        $remote_addr;
        proxy_set_header X-Scheme         $scheme;
        # nginx auth_request includes headers but not body
        proxy_set_header Content-Length   "";
        proxy_pass_request_body           off;
      }

      location /logs {
        auth_request /logs/oauth2/auth;
        error_page 401 = /logs/oauth2/sign_in;

        # pass information via X-User and X-Email headers to backend,
        # requires running with --set-xauthrequest flag
        auth_request_set $user   $upstream_http_x_auth_request_user;
        auth_request_set $email  $upstream_http_x_auth_request_email;
        proxy_set_header X-User  $user;
        proxy_set_header X-Email $email;

        # if you enabled --cookie-refresh, this is needed for it to work with auth_request
        auth_request_set $auth_cookie $upstream_http_set_cookie;
        add_header Set-Cookie $auth_cookie;

        proxy_pass http://kibana:443;
      }
    }
```

**Comment by artyomtkachenko** [comment]
Thank you very much for sharing your thoughts @Ghazgkull . 
I am planning to go the same way. I also found [this blog post ](https://blog.n1analytics.com/oauth2-lets-encrypt-and-k8s/) where it was solved with an ingress object, but it is a bit different to the Istio approach.
