### ISSUE TITLE
Running the container as non-root

### ISSUE THREAD

**Issue by jeremych1000** [pusher/oauth2_proxy#78]
## Expected Behavior
The container only contains a single binary, and therefore should be able to run without the need for root.

## Current Behavior
The container runs as root, as there is no USER defined in the Dockerfile. This is not best practice, and opens unnecessary conversations with people who utter the word 'security' every few words ;)

## Possible Solution
Add a USER line in the dockerfile.

## Steps to Reproduce (for bugs)
1.  Deploy oauth2-proxy using the helm chart 
2.  `kubectl exec -i -t <pod> -- ash`
3.  `whoami` shows `root`

## Context
Trying to use oauth2-proxy in a client environment running in Azure. Currently using Kubernetes. Client security team are very conscious of containers running as root.

## Your Environment
Azure AKS, Kubernetes cluster, oauth2-proxy deployed using official helm chart found at https://github.com/helm/charts/tree/master/stable/oauth2-proxy

- Version used:
aks: Kubernetes v1.11.6
repository: "quay.io/pusher/oauth2_proxy"
tag: "v3.1.0"

**Comment by jeremych1000** [comment]
Will this change be included in the next release? 
Right now I can't version lock the docker image as this is only in latest/master.

**Comment by JoelSpeed** [comment]
Yes, I will be creating a release soon, ideally within a week
