### ISSUE TITLE
oauth2 does not honour http_proxy environment variable

### ISSUE THREAD

**Issue by ndevireddy** [pusher/oauth2_proxy#80]
Oauth2 command line should detect the environment variables such as http_proxy and https_proxy and use them while accessing the redirection urls.

We are running oauth2 behind a corporate proxy and it is having trouble reaching our corporate github server. I do not see any option to provide http_proxy info in the oauth2.conf file

oauth2 command line should honour the environment variables ( system level ) and use them while initiating http requests.

run oauth2 from a host behind corporate proxy and use redirection url like google.com or github.com which needs to be routed via a proxy.

1.  
2.  
3.  
4.  

## Context

Redhat Linux 6.

- Version used:  v3.1.0

**Comment by ploxiln** [comment]
Did you happen to use the flag `-ssl-insecure-skip-verify`? The go default http transport _should_ honor the `http_proxy` environment variable, but if you use that flag, it is replaced by a transport which incidentally does not.

**Comment by martinbalint** [comment]
I just needed to debug traffic with Fiddler and this bug blocked me.
