### ISSUE TITLE
How to run as a docker container

### ISSUE THREAD

**Issue by pappavic** [pusher/oauth2_proxy#81]
I am trying to run this as a docker container, here is my command:

```
docker run -P quay.io/pusher/oauth2_proxy \
    --cookie-secure=false \
    --upstream="http://internal.website.com/" \
    --http-address="127.0.0.1:4180" \
    --redirect-url="http://internal.website.com/oauth2/callback" \
    --cookie-secret=<secret> \
    --client-id=<google OAuth client id> \
    --client-secret=<google Oauth secret>
```

The output tells me it's listening to 127.0.0.1:4180, but when I curl that address. I'm getting 
`Failed to connect to 127.0.0.1 port 4180: Connection refused`

How do I get to the home page shown at the top of the README?

**Comment by ploxiln** [comment]
`-P` won't work, for a couple reasons:
  * there are no EXPOSE directives in the dockerfile
  * `-P` uses random ports, not matching ports

so replace `-P` with `-p 4180:4180` or alternatively with `--net=host`

**Comment by pappavic** [comment]
Ah that makes sense. After adding that port mapping I'm now getting:
`curl: (52) Empty reply from server`

**Comment by ploxiln** [comment]
look at container logs. it's not running because you're missing the `--email-domain=...` option

**Comment by pappavic** [comment]
I have used --email-domain option and logs don't show anything after `2019/02/28 05:29:33 http.go:52: HTTP: listening on 127.0.0.1:4180`

Is there a debug option for more verbose logging?

**Comment by ploxiln** [comment]
If curl is still getting "empty reply from server" then you're just dealing with docker and OS complications now. It may be easier to get started with the stand-alone binary you can download from the releases page.

**Comment by kskewes** [comment]
I think it's due to specifying `--http-address="127.0.0.1:4180".

This works for me: 
```
docker run -p 4180:4180  quay.io/pusher/oauth2_proxy:v3.1.0     --cookie-secure=false     --upstream="file:///dev/null"     --http-address="0.0.0.0:4180"     --redirect-url="http://internal.website.com/oauth2/callback"     --cookie-secret=changeme     --client-id=changeme     --client-secret=changeme --email-domain=*
```

**Comment by gripenk** [comment]
I also meet this problem. I can use pre-release binary to run the proxy. But I meet issue#53, thus, I try to use docker image

env: CentOs 6.10, Docker version 1.7.1

docker run --name oauth -p 4180:4180 -d quay.io/pusher/oauth2_proxy -provider oidc -client-id changeit -client-secret changeit -redirect-url https://myhost.example.com/oauth2/callback  -oidc-issuer-url https://GITLAB  -cookie-secret changeit -email-domain * -basic-auth-password changeit -pass-basic-auth true -upstream http://127.0.0.1:8000/ -http-address "0.0.0.0:4180" -cookie-name example.com -cookie-doamin example.com  --cookie-secure true

**Comment by syscll** [comment]
Closing as it looks like this was a docker/config misconfiguration and has now been resolved.
