### ISSUE TITLE
Running On GKE

### ISSUE THREAD

**Issue by benfdking** [pusher/oauth2_proxy#86]
Ideally, I would like oauth2_proxy to work, with it exposed to the internet on GKE with an GCP ingress and then pointing on to a different service upstream.

## Expected Behavior

Setup as sidecar for the deployment of interest and point a to the container of interest as an upstream.

## Current Behavior

The service is marked as unhealthy by the ingress. 

## Possible Solution

Somehow make root path return a 200. 

## Steps to Reproduce (for bugs)

1.  Create GKE Cluster
2. Create image with oauth2_proxy side car
3. Point service to side car
4. Point ingress to service.

## Your Environment

- Version used:

**Comment by benfdking** [comment]
The way I have currently got it working is by putting the following in between the GKE ingress and the reverse proxy.

```go
func main() {
	sp := os.Getenv("SERVER_PORT")
	if sp == "" {
		log.Fatal("empty SERVER_PORT")
	}
	t := os.Getenv("TARGET_ADDRESS")
	if t == "" {
		log.Fatal("empty TARGET_ADDRESS")
	}
	u, err := url.Parse(t)
	if err != nil {
		log.Fatal("Error parsing target", t)
	}

	r := httputil.NewSingleHostReverseProxy(u)
	r.ModifyResponse = ModifyResponse

	if err := http.ListenAndServe(":"+sp, r); err != nil {
		log.Fatal()
	}
}

// ModifyResponse modifies root statuscode if it is forbidden
func ModifyResponse(response *http.Response) error {
	p := response.Request.URL.Path
	if response.StatusCode == http.StatusForbidden && (p == "/" || p == "") {
		response.StatusCode = http.StatusOK
	}
	return nil
}
```

**Comment by benfdking** [comment]
The proxy outputs 
```127.0.0.1 - - [05/Mar/2019:15:59:09 +0000] masked GET - "/" HTTP/1.1 "GoogleHC/1.0" 403 2511 0.000```. I presume the `GoogleHC/1.0` is an http header and could easily be handled?

**Comment by JoelSpeed** [comment]
`GoogleHC/1.0` is the user agent string, so yes, could be handled as an exception.

I'm not a GCP user so don't know how their ingress works, is there no way to configure the health check for the service to be on a non-root URL? That should be a pretty standard ingress feature I would have thought

**Comment by benfdking** [comment]
Nope, it isn't possible to set the URL. It is very very annoying! I will build a wrapper and test it. I will also try and do the `healthz` endpoint. Is there anything we could actually be health checking? Possibly pinging the oauth provider?

**Comment by JoelSpeed** [comment]
> Nope, it isn't possible to set the URL. It is very very annoying!

This is quite frankly shocking... I would have thought that would be a standard feature 😞 

> I will build a wrapper and test it. 

Sure. The alternative is to try and set the root path to return a 200 response if the user agent is `GoogleHC/1.0`, I don't know how complicated that would be to implement though

 > Is there anything we could actually be health checking?

I'm not particularly sure, I think the health endpoint just needs to respond OK to allow LBs to check the process is routable and hasn't blocked. 

> Possibly pinging the oauth provider?

Pinging the upstream provider doesn't seem like the right approach to me, if the upstream was down we would be deregistered from the LB and then we would just get the service unavailable page from the LB which in theory is less useful than the proxy throwing an error, I think 🤔

**Comment by benfdking** [comment]
> Sure. The alternative is to try and set the root path to return a 200 response if the user agent is GoogleHC/1.0, I don't know how complicated that would be to implement though

Just http middleware that returns 200 in the case that the request is `/` and that the User Agent is `GoogleHC/1.0`

**Comment by benfdking** [comment]
Addressed so can be closed. #110

**Comment by Blasterdick** [comment]
> Nope, it isn't possible to set the URL. It is very very annoying! I will build a wrapper and test it. I will also try and do the `healthz` endpoint. Is there anything we could actually be health checking? Possibly pinging the oauth provider?

It sure does have the way to change the healthcheck path. It would read it from the `readinessProbe` section on your deployment behind the service. So just:

```
readinessProbe:
    httpGet:
        path: /healthz
        port: 80
    initialDelaySeconds: 5
    periodSeconds: 5
```

**Comment by JoelSpeed** [comment]
@benfdking could you test @Blasterdick's theory and let us know the result, if it's correct I'd be tempted to remove the wrapper that was recently added as it would be unnecessary code complexity

**Comment by benfdking** [comment]
I may be wrong but I think this is still a problem though: https://github.com/kubernetes/ingress-gce/issues/674. 

The above referenced issue is still not resolved. The ingress only works if you create the deployments and services before you create the ingress. This makes the ingress rather fragile and inflexible. No service/deployment can be changed without having to recreate the ingress if you want to depend on @Blasterdick's configuration. In any case where you were to move a deployment/service including the proxy that the ingress is pointing to, you would have to recreate the ingress which can easily be 10 minutes of downtime.

**Comment by toonvd** [comment]
@benfdking you can manaually alter the statuscheck without redeploying the Ingress and update the deployment.
So applying this to an existing installation is not a problem.

I have done this on several existing projects. As for @Blasterdick his solution, I just point to Ping.

```
readinessProbe:
           httpGet:
            path: /ping
            port: 4180
            scheme: HTTP
```
