### ISSUE TITLE
Using Google Group Mailing List

### ISSUE THREAD

**Issue by cemo** [pusher/oauth2_proxy#94]
Thanks for maintaining this project first of all.

OAuth based proxy solutions started to appealing. I have a scenario in which I have a regular google group (not a gsuit based custom domain group). 

Is it possible to use google oauth with a regular google group?

**Comment by ploxiln** [comment]
If you mean "Google Groups" mailing-lists, then no, sorry.

**Comment by cemo** [comment]
Let me first of all describe my use case. Google Data Studio has ability to authenticate by Google Groups. I have created and assigned an email list to each report. However managing these reports alone is not easy. Instead of giving people report pages, I would like create a dashboard to list all reports to our users. This page a simple dummy page and However I want to authenticate users to see it by same email group. 

I have also a gsuit account. However the members I want to add to see this email group are not part of gsuit account. It seems that it is possible to include members from different organisation. 

So Is it possible to use google auth with gsuit group  including non organisation google members?

**Comment by JoelSpeed** [comment]
I think this is the same as #95, @cemo could you confirm if you are wanting the same behaviour?

**Comment by cemo** [comment]
@JoelSpeed same issue. I will close this one and follow yours since it is better described.
