### ISSUE TITLE
Panic at startup on the latest docker image

### ISSUE THREAD

**Issue by Berjou** [pusher/oauth2_proxy#98]
## Current Behavior

Updating to the latest docker image (6c9a468325f2), all my oauth2_proxy containers panic at startup.

```
goroutine 1 [running]:
github.com/pusher/oauth2_proxy/vendor/github.com/mreiferson/go-options.Resolve(0x8769c0, 0xc000043500, 0xc00001e600, 0xc0000692c0)
	/go/src/github.com/pusher/oauth2_proxy/vendor/github.com/mreiferson/go-options/options.go:86 +0xa3e
main.main()
	/go/src/github.com/pusher/oauth2_proxy/main.go:109 +0x148f
panic: interface conversion: *main.StringArray is not flag.Getter: missing method Get
```

## Steps to Reproduce (for bugs)

1.  Update to the latest docker image
2.  Reup your docker-compose without changing anything
3.  `docker-compose logs -f` shows me the previous panic stack

## Context

It seems that this bug appears on the build generated by the merge of this pull request https://github.com/pusher/oauth2_proxy/pull/92. I notice that this PR adds a new option `-proxy-websockets`. Note that setting it to `true` or `false` does not change anything.

## Your Environment

- Version used: latest docker image (6c9a468325f2)

**Comment by ploxiln** [comment]
the issue is that #92 updated the version of github.com/mreiferson/go-options being used

**Comment by Berjou** [comment]
Indeed. This is the exact commit that cause the issue: https://github.com/mreiferson/go-options/commit/0c63f026bcd6dea4266dc61d845d8db1043f75e5.
`* use Get() rather than String() for flag values`

**Comment by Berjou** [comment]
The panic is raised line 86 of https://github.com/mreiferson/go-options/blob/master/options.go:

`v = flagInst.Value.String()` -> `v = flagInst.Value.(flag.Getter).Get()`

However, `flagInst.Value` does not implement the `Getter` interface. I'm completely inexperimented in Go, but for my understanding, the problem here is that in https://github.com/pusher/oauth2_proxy/blob/master/main.go, we have

```
emailDomains := StringArray{}
whitelistDomains := StringArray{}
upstreams := StringArray{}
skipAuthRegex := StringArray{}
googleGroups := StringArray{}
```
and then, we pass these variables to `flagSet.Var()`, but a `StringArray()` does not implement the `Getter` interface.

**Comment by ploxiln** [comment]
That is correct, a `Get()` method needs to be added for the `StringArray` type

**Comment by flowstate** [comment]
I added a `Get()` to `StringArray` and it still failed exactly the same way:

`
// StringArray is a type alias for a slice of strings
type StringArray []string

// Set appends a string to the StringArray
func (a *StringArray) Set(s string) error {
	*a = append(*a, s)
	return nil
}

// String joins elements of the StringArray into a single comma separated string
func (a *StringArray) String() string {
	return strings.Join(*a, ",")
}

func (a *StringArray) Get() string {
	return strings.Join(*a, ",")
}

`

**Comment by ploxiln** [comment]
`Get()` needs to return `interface{}` explicitly.

There is actually another project with the same type and usage which adapted for this first:
https://github.com/nsqio/nsq/blob/master/internal/app/string_array.go

**Comment by Berjou** [comment]
I have just tested the latest docker image, this issue seems to be solved.

**Comment by JoelSpeed** [comment]
Thanks 😀
